// Force Power Hotbar (Steam Aspyr build 6A522E71...): ten on-screen slots bound to keys 1-0 that invoke a vanilla HUD
// quick-action, plus an in-game editor. Self-contained: controls, art and the INI template are all created by this DLL.
// Research trail and every address: patch_manager_mods/07_force_power_hotbar.md (local-setup/KOTOR-II worktree).
//
// Hooks (cdecl detours, original bytes still run):
//   0x0072CB63  CExoInputInternal::GetEvents+0x383  CaptureHotbarKey(record*, device)  -- swallow bound digits
//   0x0074B3F0  CSWGuiMainInterface::Draw           HotbarHudTick(hud)                 -- gate, config, invoke, button state
//   0x00748502  HUD ctor (FUN_00747210), just before StopLoadFromLayout  HotbarBuildButtons(panel) -- create our 57 CSWGuiLabel controls
//               at runtime (Layout[], copied from native template labels of the HUD layout) and append them to the panel's control
//               list. The panel's own Draw (0x0040EC90) then draws them with the HUD; the tick only swaps fill (border+0x74), alpha
//               (border+0x24), text and visibility. Frame/wrench art is embedded (HotbarTextures.inc) and registered as engine textures.
//
// Invoke design: the HUD's own per-group action list (hud+0x78+g*0xC, entry stride 0x3C) holds powers
// (key = spells.2da row | 0x20000000) and items (key = item object id | 0x40000000). We set the group's selection
// key (hud+0x1C7C+g*4) to the wanted entry, call FUN_00751750(hud, g, 0) (the game's own usability checks,
// feedback and action queueing), then restore the previous selection.
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stdarg.h>
#include <algorithm>
#include "HotbarConfig.h"
#include "TwoDA.h"
#include "Tlk.h"
#include "HotbarTextures.inc"   // generated by scripts/gen_hotbar_textures.py

namespace {

// ---- addresses (Steam) -----------------------------------------------------------------------------
constexpr uintptr_t HudInvokeGroup = 0x00751750;      // thiscall(hud, group 0..6, 0) RET 8
constexpr uintptr_t KeyboardDeviceGlobal = 0x0099C884; // rdata constant 0 (device-array index); verify live
constexpr uintptr_t AppGlobal = 0x00A1B4A4;           // *(app)+4 -> A ; FUN_0073fb90(A) = *(*(A+4)+0x270)
constexpr uintptr_t GetControlledCreature = 0x007E5D80; // thiscall(partyTable) -> creature (party slot 0)
// Panels that do not block gameplay hotkeys (RTTI vtables): messages, fade, pause, auto-pause
constexpr uintptr_t PanelWhitelist[] = { 0x0099E5EC, 0x009A044C, 0x009A7BAC, 0x009A8FCC };

// ---- HUD / manager layout (EKC K2_CONFIG; verified live) -------------------------
constexpr int Hud_Manager = 0x1C;
constexpr int Panel_Flags = 0x48;
constexpr int PanelIgnoredByInput = 0x600;
constexpr int Mgr_Panels = 0x88, Mgr_PanelCount = 0x8C, Mgr_Modals = 0x94, Mgr_ModalCount = 0x98;
constexpr int Hud_GroupLists = 0x78;    // {entries ptr @+0, count @+4, cap @+8} * 7 groups
constexpr int Hud_GroupSel = 0x1C7C;    // int key per group, -1 = none
constexpr int Hud_ActiveGroup = 0x1C98;
constexpr int EntryStride = 0x3C;
constexpr int Entry_Key = 0x8, Entry_Flags = 0x30;
constexpr int MaxEntries = 256;

// ---- on-screen buttons: CSWGuiLabel widgets, see 07_force_power_hotbar.md "Bottom-bar UX" ---------
constexpr uintptr_t FnLabelCtor = 0x00419740;     // CSWGuiLabel ctor, thiscall(ECX=this), no stack args; object size 0x148
constexpr uintptr_t FnInitControl = 0x0040F620;   // thiscall(panel, ctl, CExoString* tag, addToList, scale) RET 16
constexpr uintptr_t FnExoCtor = 0x00733570, FnExoDtor = 0x00733780;
constexpr uintptr_t FnNew = 0x00919723;           // cdecl(size)
constexpr uintptr_t FnLoadImage = 0x0047EB60;     // cdecl(resref char[17]) -> new image wrapper (8 bytes) each call: pooled
constexpr uintptr_t LabelVtable = 0x009878BC, BorderVtable = 0x009875BC;
constexpr int LabelSize = 0x148;
constexpr int Label_Border = 0x60;                // embedded CSWGuiBorder
constexpr int Ctl_Flags = 0x48;                   // bit1 = visible (panel Draw skips the control otherwise)
constexpr int Ctl_Id = 0x54;
constexpr int Border_W = 0xC, Border_H = 0x10, Border_Alpha = 0x24, Border_Fill = 0x74;
constexpr int Panel_CtlArray = 0x24, Panel_CtlCount = 0x28;
constexpr int ButtonCount = 10;
constexpr uintptr_t ProjectionFlag = 0x00A1B9F0;
// (FUN_0073FEA0 screen-info getter is a THISCALL reading [ecx+0x274]: never call it without a valid this)
constexpr uintptr_t GuiRefW = 0x009F4390, GuiRefH = 0x009F4394;   // ints (800, 600): the 800x600 layout space
// Our controls are created at runtime and appended to the HUD panel's control list (see Layout[] and createLabel). Offsets below are
// positions in Layout[] (= list index - base, base = native control count). The tooltip pair is last so it draws above the picker
// (panel Draw walks the list in ascending order).
constexpr int BgOff0 = 0, IcOff0 = BgOff0 + ButtonCount;                    // slot frames, slot icons
constexpr int EditOff = IcOff0 + ButtonCount, PbgOff = EditOff + 1, TitleOff = EditOff + 2, TabOff0 = EditOff + 3, TabCount = 3;
constexpr int PrevOff = TabOff0 + TabCount, NextOff = PrevOff + 1, ClearOff = PrevOff + 2;
constexpr int CellCount = 8, CellBgOff0 = ClearOff + 1, CellIcOff0 = CellBgOff0 + CellCount;
constexpr int NumOff0 = CellIcOff0 + CellCount;                              // key-digit labels (own labels so the digit can sit above-left of the icon)
constexpr int TipBgOff = NumOff0 + ButtonCount, TipOff = TipBgOff + 1;       // hover tooltip frame + text
constexpr int ControlCount = TipOff + 1;                                     // 57
constexpr int EditorControlCount = CellIcOff0 + CellCount - EditOff;         // 25: the editor is enabled only when all of them exist
constexpr int CellTipBase = 100, ToggleTipId = 200, OtherTipBase = 210;                  // tooltip owner ids >= this are picker cells
constexpr uintptr_t FnTextSet = 0x00416E30;       // thiscall(ECX = CSWGuiText+0x18 = label+0xF0, CExoString*) RET 4: sets text + relayouts
constexpr uintptr_t GuiSoundMgrGlobal = 0x00A1B49C, FnPlayGuiSound = 0x004122A0;   // thiscall(ECX = *GuiSoundMgrGlobal, char idx) RET 4; idx 1 = the control mouse-enter sound (FUN_00418750 / FUN_00418FE0)
constexpr uintptr_t TextVtable = 0x009876B4;
constexpr int Label_Text = 0xD8, Text_Renderer = 0x14, Text_StringSub = 0x18;
constexpr DWORD TipDelayMs = 450;
constexpr int TipCharW = 21, TipLineH = 32, TipPad = 22, TipWrap = 38, TipMaxDescLines = 3;   // px estimates for dialogfont16x16 at 2.667 px/unit
const char* const Spells2daPath = "override/spells.2da";
const char* const TlkPath = "dialog.tlk";
// Art embedded in the DLL (HotbarTextures.inc) and registered as engine textures under these names (ensureTextures).
const char* const FrameResref = "fph_slot", *const FrameHiResref = "fph_slot_hi";   // slot / tab / cell frame, normal + hover
const char* const EditResref = "fph_edit", *const EditHiResref = "fph_edit_hi";     // thin wrench toggle, normal + active
constexpr double EditBoxUnits = 38.0, PickBoxUnits = 112.0, BoxPadUnits = 8.0, TitleUnits = 22.0;   // must match LBL_HOTBARPBG / PTITLE in Layout[]
constexpr float EmptyFrameAlpha = 0.45f;
constexpr DWORD SettleMs = 1500;                  // after a character switch the HUD action lists lag behind: unresolved slots stay hidden, checked every frame
constexpr int ButtonRefreshFrames = 8;            // entry re-resolve interval (usable/dim state changes are slow)
constexpr float DimAlpha = 0.35f;

// ---- logging: force_power_hotbar_log.txt in the game dir, capped ------------------------------------
int g_logLines = 0;
long g_frameForLog = 0;   // mirrors g_frame so every line is frame-stamped
constexpr int MaxLogLines = 60000;
const char* const LogPath = "force_power_hotbar_log.txt", *const LogPrevPath = "force_power_hotbar_log.1.txt";   // previous session is kept as .1
void logf(const char* fmt, ...) {
    if (g_logLines >= MaxLogLines) { if (g_logLines == MaxLogLines) { ++g_logLines; FILE* f = fopen(LogPath, "a"); if (f) { fputs("LOG CAP REACHED -- further lines dropped\n", f); fclose(f); } } return; }
    FILE* f = fopen(LogPath, "a");
    if (!f) return;
    ++g_logLines;
    fprintf(f, "[%lu f%ld] ", (unsigned long)GetTickCount(), g_frameForLog);
    va_list ap; va_start(ap, fmt); vfprintf(f, fmt, ap); va_end(ap);
    fputc('\n', f); fclose(f);
}

template <typename T> bool readAt(uintptr_t base, int off, T* out) {
    if (base == 0 || IsBadReadPtr(reinterpret_cast<const void*>(base + off), sizeof(T))) return false;
    *out = *reinterpret_cast<const T*>(base + off);
    return true;
}
int rdInt(uintptr_t base, int off, int dflt = 0) { int v; return readAt(base, off, &v) ? v : dflt; }

// Guarded CExoString {char* text; int len} read; empty on anything implausible.
std::string readCExoString(uintptr_t addr) {
    int p, len;
    if (!readAt(addr, 0, &p) || !readAt(addr, 4, &len)) return "";
    if (len <= 0 || len > 80 || p == 0 || IsBadReadPtr(reinterpret_cast<const void*>(p), len)) return "";
    std::string s(reinterpret_cast<const char*>(p), len);
    while (!s.empty() && s.back() == '\0') s.pop_back();   // engine lengths include the trailing NUL (live-verified)
    if (s.empty()) return "";
    for (unsigned char c : s) if (c < 0x20 || c > 0x7E) return "";
    return s;
}

// ---- action decode (shared by the INI and the resolver) --------------------------------
struct Entry { int group, index, key, flags; std::string name, icon; hb::ActionRef ref; };

hb::ActionRef decodeKey(int key, const std::string& name) {
    hb::ActionRef r;
    if (key & 0x40000000) { r.kind = hb::K_Item; r.name = hb::normalizeItemName(name); if (r.name.empty()) r.kind = hb::K_None; }
    else if (key & 0x20000000) { r.kind = hb::K_Spell; r.id = key & 0x1FFFFFFF; }
    else { r.kind = hb::K_Other; r.id = key; }
    return r;
}

// Reads group g's entry list from the hud (guarded). Returns count read.
int readGroup(uintptr_t hud, int g, std::vector<Entry>* out) {
    out->clear();
    int base = rdInt(hud, Hud_GroupLists + g * 12), count = rdInt(hud, Hud_GroupLists + 4 + g * 12);
    if (count < 0 || count > MaxEntries) { logf("readGroup g=%d: implausible count=%d base=%08x", g, count, (unsigned)base); return 0; }
    if (base == 0 || count == 0) return 0;
    for (int i = 0; i < count; ++i) {
        uintptr_t e = (uintptr_t)base + (uintptr_t)i * EntryStride;
        if (IsBadReadPtr(reinterpret_cast<const void*>(e), EntryStride)) { logf("readGroup g=%d: entry %d at %08x unreadable, stopping", g, i, (unsigned)e); break; }
        Entry en; en.group = g; en.index = i; en.key = rdInt(e, Entry_Key); en.flags = rdInt(e, Entry_Flags);
        en.name = readCExoString(e);
        { char ib[17] = {0}; if (!IsBadReadPtr(reinterpret_cast<const void*>(e + 0x1C + 4), 16)) { memcpy(ib, reinterpret_cast<const void*>(e + 0x20), 16); for (int k = 0; k < 16; ++k) if (ib[k] && (ib[k] < 0x20 || ib[k] > 0x7E)) ib[k] = '?'; } en.icon = ib; }
        en.ref = decodeKey(en.key, en.name);
        out->push_back(en);
    }
    return (int)out->size();
}

// ---- state --------------------------------------------------------------------------------------------
const char* IniPath = "force_power_hotbar.ini";
hb::Config g_cfg;
#define VLOG(...) do { if (g_cfg.general.verbose) logf(__VA_ARGS__); } while (0)   // VERBOSE tier: only with Verbose=1 in the INI
long long g_cfgMtime = -2;
DWORD g_lastCfgCheck = 0;
std::string g_charKey;                 // key of the controlled creature
DWORD g_charChangeTick = 0;            // GetTickCount() of the last character-key change (0 = none yet)
volatile bool g_slotBound[hb::Slots];   // Bottom row (row 0)
volatile DWORD g_hudTick = 0;          // last HUD tick time
volatile bool g_hudGateOk = false;
uintptr_t g_hud = 0;
int g_kbDevice = 0;
long g_frame = 0;

struct Req { int slot; };
Req g_ring[16]; int g_ringHead = 0, g_ringTail = 0;  // single producer (input) / consumer (tick) on the game thread
bool g_downSwallowed[256];
bool g_ctrl = false, g_alt = false, g_shift = false;

// ---- gate: gameplay HUD is the active panel (EKC IsGameplayHudActive port, guarded) -------------------
bool isIgnored(uintptr_t panel) { return (rdInt(panel, Panel_Flags) & PanelIgnoredByInput) != 0; }
bool isWhitelisted(uintptr_t panel) {
    uintptr_t vt; if (!readAt(panel, 0, &vt)) return false;
    for (uintptr_t w : PanelWhitelist) if (vt == w) return true;
    return false;
}
const char* gateWhy = "";
bool gameplayHudActive(uintptr_t hud) {
    uintptr_t mgr; if (!readAt(hud, Hud_Manager, &mgr) || !mgr) { gateWhy = "no manager"; return false; }
    int modals = rdInt(mgr, Mgr_Modals), modalCount = rdInt(mgr, Mgr_ModalCount);
    if (modalCount < 0 || modalCount > 64) { gateWhy = "bad modal count"; return false; }
    for (int i = modalCount - 1; i >= 0; --i) {
        uintptr_t p; if (!readAt((uintptr_t)modals, i * 4, &p) || !p) { gateWhy = "bad modal ptr"; return false; }
        if (!isIgnored(p)) { gateWhy = "modal open"; return false; }
    }
    int panels = rdInt(mgr, Mgr_Panels), panelCount = rdInt(mgr, Mgr_PanelCount);
    if (panelCount < 0 || panelCount > 256) { gateWhy = "bad panel count"; return false; }
    for (int i = panelCount - 1; i >= 0; --i) {
        uintptr_t p; if (!readAt((uintptr_t)panels, i * 4, &p) || !p) { gateWhy = "bad panel ptr"; return false; }
        if (isIgnored(p)) continue;
        if (p == hud) { gateWhy = "hud on top"; return true; }
        if (!isWhitelisted(p)) { gateWhy = "other panel on top"; return false; }
    }
    gateWhy = "hud not in list"; return false;
}

void logPanels(uintptr_t hud) {
    uintptr_t mgr; if (!readAt(hud, Hud_Manager, &mgr) || !mgr) return;
    int modals = rdInt(mgr, Mgr_Modals), modalCount = rdInt(mgr, Mgr_ModalCount);
    int panels = rdInt(mgr, Mgr_Panels), panelCount = rdInt(mgr, Mgr_PanelCount);
    VLOG("  panels: hud=%08x hudvt=%08x mgr=%08x modals=%d panels=%d", (unsigned)hud, rdInt(hud, 0), (unsigned)mgr, modalCount, panelCount);
    for (int i = 0; i < modalCount && i < 16; ++i) { int p = rdInt((uintptr_t)modals, i * 4); VLOG("    modal[%d]=%08x vt=%08x flags=%x", i, p, rdInt(p, 0), rdInt(p, Panel_Flags)); }
    for (int i = 0; i < panelCount && i < 32; ++i) { int p = rdInt((uintptr_t)panels, i * 4); VLOG("    panel[%d]=%08x vt=%08x flags=%x", i, p, rdInt(p, 0), rdInt(p, Panel_Flags)); }
}

// ---- controlled creature + characterKey ---------------------------------------------------------------
int g_partyCount = 0;   // member count seen by the last controlledCreature() call
uintptr_t controlledCreature() {
    static const char* lastFail = nullptr;
    auto fail = [&](const char* why) { if (lastFail != why) { lastFail = why; logf("creature: unavailable (%s)", why); } return (uintptr_t)0; };
    int app; if (!readAt(AppGlobal, 0, &app) || !app) return fail("app global null");
    int a; if (!readAt(app, 4, &a) || !a) return fail("app+4 null");
    int b; if (!readAt(a, 4, &b) || !b) return fail("a+4 null");
    int party; if (!readAt(b, 0x270, &party) || !party) return fail("party table null");
    g_partyCount = rdInt(party, 0);
    if (g_partyCount <= 0) return fail("party count 0");   // member count
    lastFail = nullptr;
    using Fn = uintptr_t(__thiscall*)(void*);
    return reinterpret_cast<Fn>(GetControlledCreature)(reinterpret_cast<void*>(party));
}

std::string computeCharacterKey() {
    uintptr_t c = controlledCreature();
    if (!c) return "";
    unsigned oid = (unsigned)rdInt(c, 4);
    if (oid == 0xFFFFFFFFu || oid == 0) {   // invalid object id: transient during loads, never a real character
        static unsigned lastBad = 1; static int badLogs = 0;
        if (lastBad != oid * 31u + (unsigned)g_partyCount && badLogs < 30) { lastBad = oid * 31u + (unsigned)g_partyCount; ++badLogs; logf("character: creature %p has invalid object id %08x (party members=%d)", (void*)c, oid, g_partyCount); }
        // A one-member party is always the player character (the Exile, whose valid id is fffffffd): the id can read 0xFFFFFFFF for a whole session
        // (seen on the Ebon Hawk), which would otherwise leave the character unidentified and refuse every assignment.
        if (oid == 0xFFFFFFFFu && g_partyCount == 1) return "objfffffffd";
        return "";
    }
    char b[24]; snprintf(b, sizeof b, "obj%08x", oid);
    return b;
}

// ---- config: load / hot-reload / active slots --------------------------------------------------------
void writeTemplateIni() {
    hb::Config t; t.profile("Default");   // release defaults from hb::General: Invoke=1, Verbose=0, AutoFill=0
    t.Save(IniPath);
    logf("cfg: wrote template %s", IniPath);
}

// Effective Bottom row (row 0): the configured binding, else (AutoFill=1) the character's next known power not bound elsewhere on the bar.
hb::ActionRef g_eff[hb::Slots]; bool g_effAuto[hb::Slots]; unsigned g_effHash = 0;

void recomputeBound() {
    int bound = 0;
    for (int s = 0; s < hb::Slots; ++s) {
        if (g_cfg.general.autoFill) continue;   // owned by refreshEffective
        hb::ActionRef a = g_cfg.slotFor(g_charKey, 0, s);
        g_slotBound[s] = !a.empty(); if (!a.empty()) ++bound;
    }
    logf("cfg: profile for character '%s' -> %d/%d slots bound", g_charKey.c_str(), bound, hb::Slots);
    if (g_cfg.general.verbose) for (int r = 0; r < hb::Rows; ++r) for (int s = 0; s < hb::Slots; ++s) {
        hb::ActionRef a = g_cfg.slotFor(g_charKey, r, s);
        if (!a.empty()) logf("    %s = %s", hb::SlotKeyName(r, s).c_str(), hb::Format(a).c_str());
    }
}

void refreshEffective(uintptr_t hud) {
    std::vector<hb::ActionRef> explicitRefs;
    for (int i = 0; i < hb::Slots; ++i) { hb::ActionRef a = g_cfg.slotFor(g_charKey, 0, i); if (!a.empty()) explicitRefs.push_back(a); }
    std::vector<hb::ActionRef> autos;
    if (g_cfg.general.autoFill) {
        std::vector<Entry> es; readGroup(hud, 0, &es);
        for (auto& e : es) {
            if ((e.key & 0x40000000) || !(e.key & 0x20000000)) continue;   // known Force powers only (no items, no mode toggles)
            bool dup = false; for (auto& x : explicitRefs) if (hb::Same(x, e.ref)) dup = true;
            if (!dup) autos.push_back(e.ref);
        }
        // then the selected entry of each item group (1 medpac/stim, 2 shield, 3 mine), like the native quick bar's current pick
        for (int g = 1; g <= 3; ++g) {
            std::vector<Entry> is; readGroup(hud, g, &is);
            if (is.empty()) continue;
            unsigned selKey = (unsigned)rdInt(hud, Hud_GroupSel + g * 4);
            const Entry* pick = &is[0]; for (auto& e : is) if ((unsigned)e.key == selKey) { pick = &e; break; }
            bool dup = false; for (auto& x : explicitRefs) if (hb::Same(x, pick->ref)) dup = true;
            for (auto& x : autos) if (hb::Same(x, pick->ref)) dup = true;
            VLOG("eff: autofill group %d pick key=%08x '%s' ref=%s%s", g, (unsigned)pick->key, pick->name.c_str(), hb::Format(pick->ref).c_str(), dup ? " (dup, skipped)" : "");
            if (!dup && !pick->ref.empty()) autos.push_back(pick->ref);
        }
    }
    size_t next = 0; unsigned h = 2166136261u; int nAuto = 0;
    for (int s = 0; s < hb::Slots; ++s) {
        hb::ActionRef a = g_cfg.slotFor(g_charKey, 0, s); bool isAuto = false;
        if (a.empty() && !a.blank && next < autos.size()) { a = autos[next++]; isAuto = true; ++nAuto; }   // explicit "none" stays empty
        g_eff[s] = a; g_effAuto[s] = isAuto; g_slotBound[s] = !a.empty();
        h = (h ^ (unsigned)hb::Format(a).size() ^ ((unsigned)a.id << 8) ^ (isAuto ? 0x5000000u : 0)) * 16777619u;
        for (char c : hb::Format(a)) h = (h ^ (unsigned char)c) * 16777619u;
    }
    if (h != g_effHash) {
        g_effHash = h;
        logf("eff: character '%s' autofill=%d explicit=%d auto=%d", g_charKey.c_str(), g_cfg.general.autoFill, (int)explicitRefs.size(), nAuto);
        for (int s = 0; s < hb::Slots; ++s) if (!g_eff[s].empty()) logf("    Bottom%c = %s%s", "1234567890"[s], hb::Format(g_eff[s]).c_str(), g_effAuto[s] ? " (auto)" : "");
    }
}

void checkConfig(bool force) {
    DWORD now = GetTickCount();
    if (!force && now - g_lastCfgCheck < 1000) return;
    g_lastCfgCheck = now;
    long long mt = hb::Config::mtimeOf(IniPath);
    if (mt == -1 && g_cfgMtime == -2) { writeTemplateIni(); mt = hb::Config::mtimeOf(IniPath); }
    if (mt == g_cfgMtime) return;
    hb::Config c;
    if (!c.Load(IniPath)) { logf("cfg: cannot read %s (mtime=%lld, keeping previous)", IniPath, mt); g_cfgMtime = mt; return; }
    g_cfg = c; g_cfgMtime = mt;
    logf("cfg: loaded %s: invoke=%d verbose=%d kbdev=%d profiles=%d warnings=%d",
         IniPath, g_cfg.general.invoke, g_cfg.general.verbose, g_cfg.general.keyboardDevice,
         (int)g_cfg.profiles.size(), (int)g_cfg.warnings.size());
    for (auto& w : g_cfg.warnings) logf("cfg: WARNING %s", w.c_str());
    int dev = g_cfg.general.keyboardDevice;
    g_kbDevice = dev >= 0 ? dev : rdInt(KeyboardDeviceGlobal, 0, 0);
    recomputeBound();
}

// ---- resolver + invoker -------------------------------------------------------------------------------
bool resolve(uintptr_t hud, const hb::ActionRef& want, Entry* out) {
    std::vector<Entry> es;
    for (int g = 0; g < 6; ++g) {
        readGroup(hud, g, &es);
        for (auto& e : es) if (hb::Same(e.ref, want)) { *out = e; return true; }
    }
    return false;
}

void invokeEntry(uintptr_t hud, const Entry& e) {
    int* sel = reinterpret_cast<int*>(hud + Hud_GroupSel + e.group * 4);
    int* active = reinterpret_cast<int*>(hud + Hud_ActiveGroup);
    if (IsBadWritePtr(sel, 4) || IsBadWritePtr(active, 4)) { logf("  invoke: hud selection not writable"); return; }
    VLOG("  invoke: pre group=%d key=%08x sel=%08x active=%d", e.group, (unsigned)e.key, (unsigned)*sel, *active);
    int oldSel = *sel, oldActive = *active;
    *sel = e.key;
    using Fn = void(__thiscall*)(void*, int, int);
    reinterpret_cast<Fn>(HudInvokeGroup)(reinterpret_cast<void*>(hud), e.group, 0);
    logf("  invoke: returned group=%d key=%08x (sel before=%08x after=%08x active before=%d after=%d)", e.group, (unsigned)e.key, (unsigned)oldSel, (unsigned)*sel, oldActive, *active);
    if (*sel == e.key) { *sel = oldSel; logf("  invoke: selection restored to %08x", (unsigned)oldSel); }
    else logf("  invoke: selection changed by the game to %08x, NOT restoring", (unsigned)*sel);
    *active = oldActive;
}

void drainRing(uintptr_t hud) {
    while (g_ringTail != g_ringHead) {
        Req r = g_ring[g_ringTail]; g_ringTail = (g_ringTail + 1) % 16;
        hb::ActionRef a = g_eff[r.slot];   // Bottom row (row 0) only
        std::string sk = hb::SlotKeyName(0, r.slot);
        if (a.empty()) { logf("slot %s: unbound now (config changed?)", sk.c_str()); continue; }
        Entry e;
        if (!resolve(hud, a, &e)) {
            logf("slot %s: %s -> entry not available for '%s'; available now:", sk.c_str(), hb::Format(a).c_str(), g_charKey.c_str());
            std::vector<Entry> es;
            static int availLogs = 0;   // per process: the full list is only worth dumping a few times
            for (int g = 0; g < 6; ++g) { readGroup(hud, g, &es); for (auto& x : es) if (availLogs < 20) { ++availLogs; logf("    avail g%d.%d key=%08x %s \"%s\"", g, x.index, (unsigned)x.key, hb::Format(x.ref).c_str(), x.name.c_str()); } }
            continue;
        }
        logf("slot %s: %s -> group %d index %d key=%08x flags=%08x usable=%d %s", sk.c_str(), hb::Format(a).c_str(), e.group, e.index,
             (unsigned)e.key, (unsigned)e.flags, e.flags & 1, g_cfg.general.invoke ? "INVOKING" : "(Invoke=0: would invoke)");
        if (g_cfg.general.invoke) invokeEntry(hud, e);
    }
}

// ---- on-screen buttons -----------------------------------------------------------------------------------
// Each slot = three labels: a frame (LBL_HOTBARBG<d>, drawn first) showing "fph_slot" / "fph_slot_hi" (hover), the icon label
// (LBL_HOTBAR<d>) on top and the key digit (LBL_HOTBARNUM<d>). All are hidden when the HUD gate is closed.
using InitCtlFn = void(__thiscall*)(void*, void*, void*, int, int);
using CExoCtorFn = void*(__thiscall*)(void*, const char*);
using CExoDtorFn = void(__thiscall*)(void*);
using LabelCtorFn = void(__fastcall*)(void*);
using NewFn = void*(__cdecl*)(unsigned);
using LoadImageFn = void*(__cdecl*)(const char*);

struct Widget {
    unsigned char* ctl = nullptr;   // 0x148-byte CSWGuiLabel (never freed: the panel dtor does not delete list entries)
    float baseAlpha = 1.0f;         // border alpha as loaded from the GFF
    int visible = -1;               // last applied: -1 unknown, 0 hidden, 1 shown
    float alpha = -1.0f;            // last applied border alpha
    std::string icon;               // last applied fill resref ("" = none)
    std::string why;                // last logged reason for hidden/shown
    std::string text;               // last applied runtime text (picker widgets)
};
struct Button { Widget bg, ic, num; bool avail = false; Entry entry; };
// ---- in-game editor state (the editor and the per-HUD hover/refresh/repeat timers live in Bar, so a HUD rebuild resets them) ----
enum EditMode { M_Normal = 0, M_Edit = 1, M_Pick = 2 };
const char* const ModeName[] = { "Normal", "Edit", "Pick" };
struct Cell { Widget bg, ic; bool avail = false; Entry entry; };
struct Editor {
    int mode = M_Normal, slot = -1, tab = 0, off = 0;   // off = index of the first visible picker entry (scroll position)
    std::vector<Entry> list; unsigned sig = 0; long lastRefresh = -1000;
    int over = -1; DWORD overStart = 0;
    std::string msg;                  // transient message shown in the title (e.g. a refused save)
    int pbgRect[4] = {0, 0, 0, 0};    // group background rect as bound (pick-mode size, engine px)
    int placed = -1;                  // last applied layout: 0 edit (compact), 1 pick (full)
    int othLast = -1; DWORD othSince = 0;                         // hovered picker control (tab / arrow / Clear) + when the hover began
    bool toggleWasOver = false; DWORD toggleSince = 0;            // cursor over the wrench toggle + since when
    DWORD arrowHeldSince = 0, arrowLastRep = 0; int arrowHeld = 0; // arrow-hold auto-repeat state
};
struct Bar {
    uintptr_t panel = 0; int built = 0; Button b[ButtonCount]; Widget tipBg, tip; int tipSlot = -1; std::string tipText;
    Widget edit, pbg, title, tab[TabCount], prev, next, clear; Cell cell[CellCount]; int editBound = 0; Editor ed;
    int hoverLast = -2; DWORD hoverStart = 0;   // slot under the cursor (-2 = never evaluated) + when that hover began
    long refreshLast = -1000;                   // frame of the last button re-resolve
};
volatile bool g_editOpen = false;    // Edit or Pick mode active (read by the input hook: digits pass through, Esc is swallowed)
volatile bool g_escHit = false;      // set by the input hook when it swallowed an Esc key-down
Bar g_bar;

// one engine image object per icon resref, created lazily and never released (the border only borrows the pointer).
// INVARIANT: the border owns its fill at +0x74 (border dtor 0x00414C60 / fill setter 0x00414840 delete it), and pooled images are shared
// between buttons and HUD instances. Safe only because our labels are never destroyed and the fill setter is never called on them;
// any future cleanup must null border+0x74 before freeing a label.
struct PoolEntry { char resref[17]; void* image; };
constexpr int MaxPoolImages = 256;
PoolEntry g_pool[MaxPoolImages]; int g_poolCount = 0;
void* imageFor(const char* resref) {
    for (int i = 0; i < g_poolCount; ++i) if (strcmp(g_pool[i].resref, resref) == 0) return g_pool[i].image;
    if (g_poolCount >= MaxPoolImages) { logf("img: pool full (%d), cannot load '%s'", g_poolCount, resref); return nullptr; }
    char buf[20] = {}; strncpy(buf, resref, 16);
    void* image = reinterpret_cast<LoadImageFn>(FnLoadImage)(buf);
    PoolEntry& e = g_pool[g_poolCount++]; memset(&e, 0, sizeof e); strncpy(e.resref, resref, 16); e.image = image;
    logf("img: loaded '%s' -> %p (pool %d)", resref, image, g_poolCount);
    return image;
}

char slotDigit(int slot) { return "1234567890"[slot]; }
const char* wname(const Widget& w, const Button& b) { return &w == &b.bg ? "bg" : "ic"; }

// Shown/hidden via ctl+0x48 bit1 (what the panel's Draw loop tests); logs every change.
void setVisible(Button& bt, Widget& b, int slot, bool vis, const char* why) {
    if (!b.ctl) return;
    int fl = 0; if (!readAt(reinterpret_cast<uintptr_t>(b.ctl), Ctl_Flags, &fl)) { logf("btn[%d].%s: flags unreadable, cannot set visible", slot, wname(b, bt)); return; }
    if (b.visible == (vis ? 1 : 0) && b.why == why) return;
    int nf = vis ? (fl | 2) : (fl & ~2);
    if (&b == &bt.bg) nf = vis ? (nf & ~0x20) : (nf | 0x20);   // shown frames are hit-testable so clicks on the bar do not reach the world
    if (nf != fl) *reinterpret_cast<int*>(b.ctl + Ctl_Flags) = nf;
    VLOG("btn[%d].%s key %c: %s -> %s (%s) flags %08x->%08x", slot, wname(b, bt), slotDigit(slot), b.visible < 0 ? "?" : (b.visible ? "shown" : "hidden"), vis ? "shown" : "hidden", why, (unsigned)fl, (unsigned)nf);
    b.visible = vis ? 1 : 0; b.why = why;
}

void setFill(Button& bt, Widget& b, int slot, const std::string& icon) {
    if (!b.ctl || b.icon == icon) return;
    uintptr_t border = reinterpret_cast<uintptr_t>(b.ctl) + Label_Border;
    void* image = icon.empty() ? nullptr : imageFor(icon.c_str());
    int bvt = rdInt(border, 0);
    if (bvt != (int)BorderVtable) { logf("btn[%d].%s: border vtable %08x != %08x, not setting fill '%s'", slot, wname(b, bt), (unsigned)bvt, (unsigned)BorderVtable, icon.c_str()); return; }
    int old = rdInt(border, Border_Fill);
    *reinterpret_cast<void**>(border + Border_Fill) = image;
    VLOG("btn[%d].%s key %c: fill '%s' -> '%s' image=%p (old fill %08x) border w=%d h=%d", slot, wname(b, bt), slotDigit(slot), b.icon.c_str(), icon.c_str(), image, (unsigned)old, rdInt(border, Border_W), rdInt(border, Border_H));
    b.icon = icon;
}

void setAlpha(Button& bt, Widget& b, int slot, float a) {
    if (!b.ctl || b.alpha == a) return;
    uintptr_t border = reinterpret_cast<uintptr_t>(b.ctl) + Label_Border;
    if (rdInt(border, 0) != (int)BorderVtable) { logf("btn[%d].%s: border vtable bad, not setting alpha", slot, wname(b, bt)); return; }
    *reinterpret_cast<float*>(border + Border_Alpha) = a;
    VLOG("btn[%d].%s key %c: alpha %.2f -> %.2f", slot, wname(b, bt), slotDigit(slot), b.alpha, a);
    b.alpha = a;
}

// ---- hover: poll the OS cursor against the frame's pixel rect (labels are click-through, so the game never sees the mouse over them)
HWND g_gameWnd = nullptr;
BOOL CALLBACK enumWnd(HWND h, LPARAM lp) {
    DWORD pid = 0; GetWindowThreadProcessId(h, &pid);
    if (pid == GetCurrentProcessId() && IsWindowVisible(h)) { RECT r; if (GetClientRect(h, &r) && r.right > 320 && r.bottom > 240) { *reinterpret_cast<HWND*>(lp) = h; return FALSE; } }
    return TRUE;
}
bool cursorInGame(POINT* out) {
    if (!g_gameWnd || !IsWindow(g_gameWnd)) {
        static long lastTry = -1000; if (g_frame - lastTry < 120) return false;   // failed lookups retry every 120 frames, not every frame
        lastTry = g_frame;
        g_gameWnd = nullptr; EnumWindows(enumWnd, reinterpret_cast<LPARAM>(&g_gameWnd));
        RECT r = {0, 0, 0, 0}; if (g_gameWnd) GetClientRect(g_gameWnd, &r);
        logf("hover: game window %p client=%ldx%ld", (void*)g_gameWnd, (long)r.right, (long)r.bottom);
        if (!g_gameWnd) return false;
    }
    POINT pt; if (!GetCursorPos(&pt) || !ScreenToClient(g_gameWnd, &pt)) return false;
    *out = pt; return true;
}

// ---- hover tooltip ---------------------------------------------------------------------------------------
hb::TwoDA g_spells; bool g_spellsTried = false;
hb::Tlk g_tlk; bool g_tlkTried = false;

void ensureLookups() {
    if (!g_spellsTried) {
        g_spellsTried = true;
        bool ok = g_spells.Load(Spells2daPath);
        logf("tip: %s -> %s (cols=%d rows=%d%s%s)", Spells2daPath, ok ? "ok" : "FAILED", (int)g_spells.cols.size(), (int)g_spells.rows.size(), ok ? "" : " err=", ok ? "" : g_spells.error.c_str());
    }
    if (!g_tlkTried) {
        g_tlkTried = true;
        bool ok = g_tlk.Open(TlkPath);
        logf("tip: %s -> %s (strings=%u%s%s)", TlkPath, ok ? "ok" : "FAILED", (unsigned)g_tlk.count, ok ? "" : " err=", ok ? "" : g_tlk.error.c_str());
    }
}

std::string nullish(const std::string& s) { return s == "****" ? std::string() : s; }

// greedy word wrap into '\n'-joined lines (at most maxLines, "..." when cut)
std::string wrapText(const std::string& in, int width, int maxLines) {
    std::string out, line; int lines = 0; size_t i = 0;
    while (i < in.size()) {
        size_t e = in.find(' ', i); if (e == std::string::npos) e = in.size();
        std::string w = in.substr(i, e - i); i = e + 1;
        if (!line.empty() && (int)(line.size() + 1 + w.size()) > width) {
            if (++lines >= maxLines) { line += "..."; break; }
            out += line + "\n"; line.clear();
        }
        line += (line.empty() ? "" : " ") + w;
    }
    out += line;
    return out;
}

// Descriptions start with a category/prerequisite header ("Universal Power Restricted By Armor This power ...", "Light Side Power
// Prerequisites: Character Level 6 This power ..."): drop it and keep the first sentence.
std::string shortDesc(const std::string& d) {
    size_t p = d.find(" This "); std::string t = (p != std::string::npos && p < 120) ? d.substr(p + 1) : d;
    size_t e = t.find(". "); if (e != std::string::npos) t.resize(e + 1);
    return t;
}

// Title, key, type, cost and description of slot s's current entry ('\n'-separated lines).
std::string buildTipText(char digit, const Entry& e, bool verboseLog = true) {
    std::string title = e.name; size_t par = title.rfind(" ("); if (par != std::string::npos && par > 0 && title.back() == ')') title.resize(par);
    std::string qty = e.name.size() > title.size() + 3 ? e.name.substr(title.size() + 2, e.name.size() - title.size() - 3) : "";
    std::string out = title + "\n";
    const char* kind = (e.key & 0x40000000) ? "Item" : ((e.key & 0x20000000) ? "Force Power" : "Mode");
    if (digit) out += std::string("Key: ") + digit + "   " + kind + "\n"; else out += std::string(kind) + "\n";
    if ((e.key & 0x20000000) && !(e.key & 0x40000000)) {
        ensureLookups();
        int row = e.key & 0x1FFFFFFF;
        std::string fp = nullish(g_spells.Get(row, "forcepoints")), range = g_spells.Get(row, "range");
        if (!fp.empty() && fp != "0") out += "Force Points: " + fp + "\n";
        if (range == "P") out += "Range: Personal\n"; else if (range == "T") out += "Range: Target\n";
        std::string dsc = nullish(g_spells.Get(row, "spelldesc"));
        if (!dsc.empty()) { std::string d = shortDesc(g_tlk.Get((uint32_t)atoi(dsc.c_str()))); if (!d.empty()) out += wrapText(d, TipWrap, TipMaxDescLines) + "\n"; }
        if (verboseLog) VLOG("tip: spell row %d fp='%s' range='%s' desc strref='%s'", row, fp.c_str(), range.c_str(), dsc.c_str());
    } else if (e.key & 0x40000000) {
        if (!qty.empty()) out += "Quantity: " + qty + "\n";
    }
    if (!(e.flags & 1)) out += "Not usable right now\n";
    while (!out.empty() && out.back() == '\n') out.pop_back();
    return out;
}

void setRect(Widget& w, const char* nm, int x, int y, int ww, int hh) {
    if (!w.ctl) return;
    void** vt = *reinterpret_cast<void***>(w.ctl);
    if (IsBadReadPtr(vt + 1, 4)) { logf("tip: %s vtable unreadable", nm); return; }
    int r[4] = { x, y, ww, hh };
    reinterpret_cast<void(__thiscall*)(void*, int*)>(vt[1])(w.ctl, r);
}

void setWidgetVisible(Widget& w, bool vis) {
    int fl = 0; if (!w.ctl || !readAt(reinterpret_cast<uintptr_t>(w.ctl), Ctl_Flags, &fl)) return;
    int nf = vis ? (fl | 2) : (fl & ~2);
    if (nf != fl) *reinterpret_cast<int*>(w.ctl + Ctl_Flags) = nf;
    w.visible = vis ? 1 : 0;
}

void hideTip(const char* why) {
    if (g_bar.tipSlot < 0) return;
    VLOG("tip: hide slot %d (%s)", g_bar.tipSlot, why);
    setWidgetVisible(g_bar.tipBg, false); setWidgetVisible(g_bar.tip, false);
    g_bar.tipSlot = -1;
}

void showTipText(Widget& anchor, const std::string& text, int s, int topAnchor = -1) {
    if (!g_bar.tip.ctl || !g_bar.tipBg.ctl) { logf("tip: show slot %d skipped: tooltip labels not bound (bg=%p text=%p)", s, (void*)g_bar.tipBg.ctl, (void*)g_bar.tip.ctl); g_bar.tipSlot = s; return; }
    g_bar.tipText = text;
    uintptr_t tc = reinterpret_cast<uintptr_t>(g_bar.tip.ctl), tx = tc + Label_Text;
    if (rdInt(tx, 0) != (int)TextVtable || rdInt(tx, Text_Renderer) == 0) { logf("tip: slot %d: text object bad (vt=%08x renderer=%08x), tooltip skipped", s, (unsigned)rdInt(tx, 0), (unsigned)rdInt(tx, Text_Renderer)); g_bar.tipSlot = s; return; }
    char exo[16] = {0};
    reinterpret_cast<CExoCtorFn>(FnExoCtor)(exo, text.c_str());
    reinterpret_cast<void(__thiscall*)(void*, void*)>(FnTextSet)(reinterpret_cast<void*>(tx + Text_StringSub), exo);
    reinterpret_cast<CExoDtorFn>(FnExoDtor)(exo);
    int lines = 1, maxLen = 0, cur = 0;
    for (char c : text) { if (c == '\n') { ++lines; cur = 0; } else if (++cur > maxLen) maxLen = cur; }
    int w = maxLen * TipCharW + 2 * TipPad, h = lines * TipLineH + 2 * TipPad;
    RECT cr = {0, 0, 3840, 1600}; if (g_gameWnd) GetClientRect(g_gameWnd, &cr);
    uintptr_t fc = reinterpret_cast<uintptr_t>(anchor.ctl); int fx = rdInt(fc, 4), fy = rdInt(fc, 8);
    int x = fx, y = fy - h - 12;
    if (topAnchor >= 0) y = topAnchor - h - 10;   // picker tooltips sit above the whole picker so they never cover it
    if (x + w > cr.right - 8) x = cr.right - 8 - w;
    if (x < 8) x = 8;
    if (y < 8) y = 8;
    setRect(g_bar.tipBg, "tipbg", x, y, w, h);
    setRect(g_bar.tip, "tip", x + TipPad / 2, y + TipPad / 2, w - TipPad, h - TipPad);
    setWidgetVisible(g_bar.tipBg, true); setWidgetVisible(g_bar.tip, true);
    g_bar.tipSlot = s;
    int th = 0; { void** tvt = *reinterpret_cast<void***>(tx); if (!IsBadReadPtr(tvt + 2, 4)) th = reinterpret_cast<int(__fastcall*)(void*)>(tvt[2])(reinterpret_cast<void*>(tx)); }
    VLOG("tip: show slot %d lines=%d maxLen=%d rect=[%d,%d,%d,%d] client=%ldx%ld textHeight(engine)=%d text=\"%s\"", s, lines, maxLen, x, y, w, h, (long)cr.right, (long)cr.bottom, th, text.c_str());
}

void showTipAt(Widget& anchor, const Entry& entry, char digit, int s) { showTipText(anchor, buildTipText(digit, entry), s); }

// The same short sound the native quick-action buttons play when the mouse enters them.
void playHoverSound(const char* why) {
    void* mgr = nullptr; static int logs = 0;
    if (!readAt(GuiSoundMgrGlobal, 0, &mgr) || !mgr) { if (logs < 20) { ++logs; logf("sound: manager null (%s), skipped", why); } return; }
    reinterpret_cast<void(__thiscall*)(void*, char)>(FnPlayGuiSound)(mgr, 1);
    if (logs < 40) { ++logs; VLOG("sound: hover (%s) mgr=%p", why, mgr); }
}

// Per frame: which slot (if any) the cursor is over. Only available slots highlight (frame -> "fph_slot_hi").
void updateHover(bool gate) {
    static POINT lastPt = {-1, -1}; static long lastLog = -1000;
    int over = -1; POINT pt = {0, 0};
    if (gate && cursorInGame(&pt)) {
        for (int s = 0; s < ButtonCount && over < 0; ++s) {
            const Widget& w = g_bar.b[s].bg; if (!w.ctl || !w.visible) continue;
            uintptr_t c = reinterpret_cast<uintptr_t>(w.ctl); int x = rdInt(c, 4), y = rdInt(c, 8), ww = rdInt(c, 0xC), hh = rdInt(c, 0x10);
            if (pt.x >= x && pt.x < x + ww && pt.y >= y && pt.y < y + hh) over = s;
        }
    }
    if (over != g_bar.hoverLast) { VLOG("hover: slot %d -> %d cursor=(%ld,%ld)", g_bar.hoverLast, over, (long)pt.x, (long)pt.y); g_bar.hoverLast = over; g_bar.hoverStart = GetTickCount(); hideTip("hover changed"); if (over >= 0 && (g_bar.b[over].avail || g_bar.ed.mode != M_Normal)) playHoverSound("slot"); }
    else if (g_cfg.general.verbose && (pt.x != lastPt.x || pt.y != lastPt.y) && pt.y > 1100 && g_frame - lastLog > 120) { lastLog = g_frame; logf("hover: cursor=(%ld,%ld) over=%d", (long)pt.x, (long)pt.y, over); }
    lastPt = pt;
    for (int s = 0; s < ButtonCount; ++s) {
        Button& b = g_bar.b[s]; bool hov = (s == over) && (b.avail || g_bar.ed.mode != M_Normal);
        bool selected = g_bar.ed.mode == M_Pick && g_bar.ed.slot == s;   // slot being edited stays highlighted
        if (b.bg.ctl && b.bg.visible) setFill(b, b.bg, s, (hov || selected) ? FrameHiResref : FrameResref);
    }
    {   // left click on an available slot = same request as its digit key
        static bool prevDown = false;
        bool down = gate && (GetAsyncKeyState(VK_LBUTTON) & 0x8000) != 0;
        if (down && !prevDown && over >= 0 && g_bar.ed.mode != M_Normal) logf("click: slot %d in %s mode -> handled by the editor, not invoked", over, ModeName[g_bar.ed.mode]);
        else if (down && !prevDown && over >= 0) {
            bool ok = g_bar.b[over].avail;
            logf("click: slot %d %s", over, ok ? "queued" : "ignored (no action)");
            if (ok) { int next = (g_ringHead + 1) % 16; if (next == g_ringTail) logf("click: ring full, dropped"); else { g_ring[g_ringHead] = { over }; g_ringHead = next; } }
        }
        prevDown = down;
    }
    if (over >= 0 && g_bar.b[over].avail && g_bar.tipSlot != over && GetTickCount() - g_bar.hoverStart >= TipDelayMs) showTipAt(g_bar.b[over].bg, g_bar.b[over].entry, slotDigit(over), over);
    if ((over < 0 || !g_bar.b[over].avail) && g_bar.tipSlot < CellTipBase) hideTip("no hover");
}

// Per-tick button state. gate = HUD is the active panel. Entries are re-resolved every ButtonRefreshFrames frames or when
// the cached view is stale (config/character/gate change), never per frame.
void updateButtons(uintptr_t hud, bool gate) {
    static uintptr_t lastMissingHud = 0; static bool lastGateSeen = false; static std::string lastChar = "\x01"; static int lastMode = -1;
    if (g_bar.panel != hud || g_bar.built == 0) {
        if (lastMissingHud != hud) { lastMissingHud = hud; logf("buttons: no usable bar for hud %08x (bar panel=%08x built=%d/%d) -- HUD ctor hook did not run for it, or no button bound", (unsigned)hud, (unsigned)g_bar.panel, g_bar.built, ButtonCount); }
        return;
    }
    bool settling = g_charChangeTick && GetTickCount() - g_charChangeTick < SettleMs;
    static bool wasSettling = false; bool settleEdge = settling != wasSettling; wasSettling = settling;
    bool stale = settling || settleEdge || g_frame - g_bar.refreshLast >= ButtonRefreshFrames || gate != lastGateSeen || g_charKey != lastChar || g_bar.ed.mode != lastMode;
    if (!stale) return;
    g_bar.refreshLast = g_frame; lastGateSeen = gate; lastChar = g_charKey; lastMode = g_bar.ed.mode;
    for (int s = 0; s < ButtonCount; ++s) {
        Button& b = g_bar.b[s];
        if (!b.bg.ctl && !b.ic.ctl) continue;
        if (!gate) { b.avail = false; setVisible(b, b.bg, s, false, "hud not active"); setVisible(b, b.ic, s, false, "hud not active"); setVisible(b, b.num, s, false, "hud not active"); continue; }
        // frame + digit are always shown while the HUD is active (an empty slot reads as a dim frame)
        hb::ActionRef want = g_eff[s];
        if (want.empty() && g_bar.ed.mode == M_Normal) {   // unassigned slots are invisible during play; edit mode shows them so they can be filled
            b.avail = false; setVisible(b, b.bg, s, false, "unassigned"); setVisible(b, b.ic, s, false, "unassigned"); setVisible(b, b.num, s, false, "unassigned"); continue;
        }
        Entry e; const char* state; bool have = false;
        if (want.empty()) state = "unbound";
        else if (!resolve(hud, want, &e)) {
            if (settling && g_bar.ed.mode == M_Normal) { b.avail = false; setVisible(b, b.bg, s, false, "settling after character switch"); setVisible(b, b.ic, s, false, "settling after character switch"); setVisible(b, b.num, s, false, "settling after character switch"); continue; }
            state = "entry not available";
        }
        else { have = true; state = (e.flags & 1) ? "usable" : "unusable (dimmed)"; }
        b.avail = have; if (have) b.entry = e;
        if (have && g_bar.tipSlot == s && buildTipText(slotDigit(s), e, false) != g_bar.tipText) { VLOG("tip: slot %d entry changed while hovered, refreshing", s); showTipAt(b.bg, e, slotDigit(s), s); }
        setVisible(b, b.bg, s, true, state); setVisible(b, b.ic, s, true, state); setVisible(b, b.num, s, true, state);
        setAlpha(b, b.bg, s, have ? b.bg.baseAlpha : b.bg.baseAlpha * EmptyFrameAlpha);
        setFill(b, b.ic, s, have ? e.icon : std::string());
        setAlpha(b, b.ic, s, (have && !(e.flags & 1)) ? b.ic.baseAlpha * DimAlpha : b.ic.baseAlpha);
    }
}


// ---- generic widget helpers for the editor controls (log every change) -------------------------------------
bool textObjOk(Widget& w) { uintptr_t tx = reinterpret_cast<uintptr_t>(w.ctl) + Label_Text; return rdInt(tx, 0) == (int)TextVtable && rdInt(tx, Text_Renderer) != 0; }
void wVisible(Widget& w, const char* nm, bool vis, bool hit) {
    if (!w.ctl) return;
    int fl = 0; if (!readAt(reinterpret_cast<uintptr_t>(w.ctl), Ctl_Flags, &fl)) { logf("edit: %s flags unreadable", nm); return; }
    int nf = vis ? (fl | 2) : (fl & ~2);
    nf = (vis && hit) ? (nf & ~0x20) : (nf | 0x20);   // hit-testable only while shown, so hidden controls never swallow clicks
    int v = vis ? 1 : 0;
    if (w.visible == v && nf == fl) return;
    *reinterpret_cast<int*>(w.ctl + Ctl_Flags) = nf;
    VLOG("edit: %s %s -> %s flags %08x->%08x", nm, w.visible < 0 ? "?" : (w.visible ? "shown" : "hidden"), vis ? "shown" : "hidden", (unsigned)fl, (unsigned)nf);
    w.visible = v;
}
void wFill(Widget& w, const char* nm, const std::string& icon) {
    if (!w.ctl || w.icon == icon) return;
    uintptr_t border = reinterpret_cast<uintptr_t>(w.ctl) + Label_Border;
    if (rdInt(border, 0) != (int)BorderVtable) { logf("edit: %s border vtable bad, not setting fill '%s'", nm, icon.c_str()); return; }
    void* image = icon.empty() ? nullptr : imageFor(icon.c_str());
    *reinterpret_cast<void**>(border + Border_Fill) = image;
    VLOG("edit: %s fill '%s' -> '%s' image=%p", nm, w.icon.c_str(), icon.c_str(), image);
    w.icon = icon;
}
void wAlpha(Widget& w, const char* nm, float a) {
    if (!w.ctl || w.alpha == a) return;
    uintptr_t border = reinterpret_cast<uintptr_t>(w.ctl) + Label_Border;
    if (rdInt(border, 0) != (int)BorderVtable) { logf("edit: %s border vtable bad, not setting alpha", nm); return; }
    *reinterpret_cast<float*>(border + Border_Alpha) = a;
    VLOG("edit: %s alpha %.2f -> %.2f", nm, w.alpha, a);
    w.alpha = a;
}
void wText(Widget& w, const char* nm, const std::string& text) {
    if (!w.ctl || w.text == text) return;
    if (!textObjOk(w)) { logf("edit: %s text object bad, cannot set \"%s\"", nm, text.c_str()); return; }
    uintptr_t tx = reinterpret_cast<uintptr_t>(w.ctl) + Label_Text;
    char exo[16] = {0};
    reinterpret_cast<CExoCtorFn>(FnExoCtor)(exo, text.c_str());
    reinterpret_cast<void(__thiscall*)(void*, void*)>(FnTextSet)(reinterpret_cast<void*>(tx + Text_StringSub), exo);
    reinterpret_cast<CExoDtorFn>(FnExoDtor)(exo);
    VLOG("edit: %s text \"%s\" -> \"%s\"", nm, w.text.c_str(), text.c_str());
    w.text = text;
}
bool wHit(const Widget& w, const POINT& pt) {
    if (!w.ctl || w.visible != 1) return false;
    uintptr_t c = reinterpret_cast<uintptr_t>(w.ctl); int x = rdInt(c, 4), y = rdInt(c, 8), ww = rdInt(c, 0xC), hh = rdInt(c, 0x10);
    return pt.x >= x && pt.x < x + ww && pt.y >= y && pt.y < y + hh;
}

// ---- in-game editor: Normal -> (toggle) Edit -> (slot click) Pick -> (cell / Clear) assign+save -> Edit; Esc backs out one level ----
// ---- mouse wheel over the picker: subclass the game window like Mod 1 (DirectInput never sees the wheel). Chains to the old proc; never restored.
WNDPROC g_oldProc = nullptr; volatile LONG g_wheelAccum = 0; volatile LONG g_pickRect[4] = {0, 0, 0, 0}; int g_wheelLogs = 0;
LRESULT CALLBACK wheelProc(HWND h, UINT m, WPARAM w, LPARAM l) {
    if (m == WM_MOUSEWHEEL && g_editOpen && g_pickRect[2] > 0 && GetTickCount() - g_hudTick < 300) {
        POINT pt = {(short)LOWORD(l), (short)HIWORD(l)};
        bool inside = ScreenToClient(h, &pt) && pt.x >= g_pickRect[0] && pt.x < g_pickRect[0] + g_pickRect[2] && pt.y >= g_pickRect[1] && pt.y < g_pickRect[1] + g_pickRect[3];
        if (g_wheelLogs < 40) { ++g_wheelLogs; VLOG("wheel: delta=%d client=(%ld,%ld) rect=[%ld,%ld,%ld,%ld] inside=%d", (int)(short)HIWORD(w), (long)pt.x, (long)pt.y, (long)g_pickRect[0], (long)g_pickRect[1], (long)g_pickRect[2], (long)g_pickRect[3], (int)inside); }
        if (inside) { InterlockedExchangeAdd(&g_wheelAccum, (short)HIWORD(w)); return 0; }
    }
    return CallWindowProcA(g_oldProc, h, m, w, l);
}
void ensureWheelHook() {
    if (g_oldProc || !g_gameWnd || !IsWindow(g_gameWnd)) return;
    g_oldProc = reinterpret_cast<WNDPROC>(SetWindowLongPtrA(g_gameWnd, GWLP_WNDPROC, reinterpret_cast<LONG_PTR>(wheelProc)));
    logf("wheel: subclassed window %p, old proc %p (err=%lu)", (void*)g_gameWnd, (void*)g_oldProc, g_oldProc ? 0UL : GetLastError());
}
// Group background + title: full size in Pick mode; in Edit mode a compact box (title only) hugging the bar. Sizes in units -> px via the
// background's own height (u px per unit; x and y scale equally after the aspect fix).
void moveWidget(Widget& w, const char* nm, int x, int y, int ww, int hh) {
    if (!w.ctl) return;
    setRect(w, nm, x, y, ww, hh);
    VLOG("edit: %s moved to [%d,%d,%d,%d]", nm, x, y, ww, hh);
}
void placePanel(bool pick) {
    Editor& ed = g_bar.ed;
    if (ed.placed == (pick ? 1 : 0) || ed.pbgRect[3] <= 0) return;
    const int* R = ed.pbgRect; double u = R[3] / PickBoxUnits; int pad = (int)(BoxPadUnits * u + 0.5), th = (int)(TitleUnits * u + 0.5);
    int boxH = pick ? R[3] : (int)(EditBoxUnits * u + 0.5), boxY = R[1] + R[3] - boxH;
    moveWidget(g_bar.pbg, "pbg", R[0], boxY, R[2], boxH);
    moveWidget(g_bar.title, "title", R[0] + pad, boxY + pad, R[2] - 2 * pad, th);
    ed.placed = pick ? 1 : 0;
    g_pickRect[0] = R[0]; g_pickRect[1] = boxY; g_pickRect[2] = R[2]; g_pickRect[3] = boxH;
}

void setMode(int m, int slot, const char* why) {
    Editor& ed = g_bar.ed;
    logf("edit: mode %s -> %s slot %d -> %d (%s) char='%s'", ModeName[ed.mode], ModeName[m], ed.slot, slot, why, g_charKey.c_str());
    if (m == M_Pick && ed.mode != M_Pick) { ed.off = 0; ed.sig = 0; ed.lastRefresh = -1000; g_wheelAccum = 0; }
    if (m != M_Pick) { ed.over = -1; if (g_bar.tipSlot >= CellTipBase) hideTip("picker closed"); }
    ed.mode = m; ed.slot = slot; ed.msg.clear();
    g_editOpen = (m != M_Normal);
    if (m != M_Normal) placePanel(m == M_Pick); else { g_pickRect[2] = 0; ed.placed = -1; }
}

int tabOf(const Entry& e) { return (e.key & 0x40000000) ? 1 : ((e.key & 0x20000000) ? 0 : 2); }
const char* const TabName[TabCount] = { "Power", "Item", "Mode" };

// Writes (or, with e == nullptr, clears) hotbar slot `slot` of the controlled character's profile ([Profile.<key>], key = obj%08x of the creature id) and saves the INI.
// The key is the creature object id (the Exile is objfffffffd, stable; the invalid id objffffffff seen during loads is treated as 'unknown').
bool assignSlot(uintptr_t hud, int slot, const Entry* e) {
    Editor& ed = g_bar.ed;
    checkConfig(true);   // pick up a hand edit made since the last poll before we overwrite the file
    if (!g_cfg.warnings.empty()) {
        logf("edit: assign REFUSED: config has %d warning(s); saving would drop the lines they concern", (int)g_cfg.warnings.size());
        ed.msg = "Config file has warnings - not saving (see log)"; return false;
    }
    if (g_charKey.empty()) { logf("edit: assign REFUSED: character key unknown (load in progress?)"); ed.msg = "Character not identified yet - try again"; return false; }
    hb::Profile& d = g_cfg.profile(g_charKey);   // per-character profile; slotFor falls back to Default for slots it leaves unset
    int frozen = 0;
    for (int i = 0; i < hb::Slots; ++i) if (d.slots[0][i].empty() && !d.slots[0][i].blank && !g_eff[i].empty()) { d.slots[0][i] = g_eff[i]; d.slots[0][i].blank = false; ++frozen; }
    hb::ActionRef a; if (e) a = e->ref; else a.blank = true;
    if (e && a.empty()) { logf("edit: assign REFUSED: entry '%s' has no stable ref", e->name.c_str()); ed.msg = "That entry cannot be bound"; return false; }
    g_cfg.SetSlot(g_charKey, 0, slot, a, e ? e->name : "cleared");
    static bool backedUp = false;
    if (!backedUp) { backedUp = true; BOOL ok = CopyFileA(IniPath, "force_power_hotbar.ini.bak", FALSE); logf("edit: backup %s -> force_power_hotbar.ini.bak: %s", IniPath, ok ? "ok" : "FAILED (no ini yet?)"); }
    bool ok = g_cfg.Save(IniPath);
    long long mt = hb::Config::mtimeOf(IniPath); if (ok) g_cfgMtime = mt;
    logf("edit: assign slot %d (%s) := %s; froze %d autofilled slot(s) into the profile; character '%s'; Save %s (mtime %lld)", slot, hb::SlotKeyName(0, slot).c_str(),
         e ? hb::Format(a).c_str() : "none", frozen, g_charKey.c_str(), ok ? "ok" : "FAILED", mt);
    if (!ok) { ed.msg = "Saving the config failed (see log)"; return false; }
    recomputeBound(); refreshEffective(hud);
    return true;
}

// Moves the picker to scroll offset `no` (already clamped); every real step plays the native hover sound, like the quick-action arrows.
void scrollPicker(int no, const char* why) {
    Editor& ed = g_bar.ed;
    if (no == ed.off) return;
    VLOG("edit: scroll %d -> %d (%s)", ed.off, no, why);
    ed.off = no;
    playHoverSound("picker scroll");
}

void updateEditor(uintptr_t hud, bool gate) {
    Editor& ed = g_bar.ed;
    if (g_bar.panel != hud || g_bar.built == 0 || !g_bar.editBound) return;
    static std::string lastChar = "\x01"; static bool prevDown = false; static bool lastFgOk = true;
    ensureWheelHook();
    if (lastChar != g_charKey) { if (lastChar != "\x01" && ed.mode != M_Normal) setMode(M_Normal, -1, "character changed"); lastChar = g_charKey; }
    if (!gate && ed.mode != M_Normal) setMode(M_Normal, -1, "gate closed");
    if (g_escHit) { g_escHit = false; if (ed.mode == M_Pick) setMode(M_Edit, -1, "Esc"); else if (ed.mode == M_Edit) setMode(M_Normal, -1, "Esc"); else logf("edit: Esc flag set in Normal mode (ignored)"); }

    POINT pt = {0, 0}; bool haveCur = gate && cursorInGame(&pt);
    HWND fg = GetForegroundWindow(); DWORD fgPid = 0; if (fg) GetWindowThreadProcessId(fg, &fgPid);
    bool fgOk = fg && fgPid == GetCurrentProcessId();
    if (fgOk != lastFgOk) { logf("edit: foreground window %p pid=%lu ours=%d", (void*)fg, (unsigned long)fgPid, (int)fgOk); lastFgOk = fgOk; }
    bool down = gate && fgOk && (GetAsyncKeyState(VK_LBUTTON) & 0x8000) != 0;
    bool click = down && !prevDown; prevDown = down;

    // ---- visibility of the always-present toggle and the mode-dependent parts
    bool showTitle = gate && ed.mode != M_Normal, showPick = gate && ed.mode == M_Pick;
    wVisible(g_bar.edit, "toggle", gate, true);
    {   // hover highlight: beige frame while hovered; in edit mode the beige frame is the "active" look, dimmed until hovered
        bool hov = haveCur && wHit(g_bar.edit, pt);
        wFill(g_bar.edit, "toggle", (ed.mode != M_Normal || hov) ? EditHiResref : EditResref);
        wAlpha(g_bar.edit, "toggle", (ed.mode != M_Normal && !hov) ? 0.8f : 1.0f);
    }
    wVisible(g_bar.pbg, "pbg", showTitle, true);
    wVisible(g_bar.title, "title", showTitle, true);
    for (int i = 0; i < TabCount; ++i) wVisible(g_bar.tab[i], "tab", showPick, true);
    wVisible(g_bar.prev, "prev", showPick, true); wVisible(g_bar.next, "next", showPick, true); wVisible(g_bar.clear, "clear", showPick, true);
    for (int i = 0; i < CellCount; ++i) { wVisible(g_bar.cell[i].bg, "cell.bg", showPick, true); wVisible(g_bar.cell[i].ic, "cell.ic", showPick, false); }

    // ---- hover over the tabs / arrows / Clear (highlight + short tooltip)
    Widget* ow[6] = { &g_bar.tab[0], &g_bar.tab[1], &g_bar.tab[2], &g_bar.prev, &g_bar.next, &g_bar.clear };
    static const char* const otip[6] = { "Force powers", "Items: medpacs, stims, shields, mines", "Modes and stances", "Scroll back (mouse wheel up)", "Scroll forward (mouse wheel down)", "Empty this slot" };
    int oth = -1;
    if (ed.mode == M_Pick && haveCur) for (int i = 0; i < 6 && oth < 0; ++i) if (wHit(*ow[i], pt)) oth = i;
    {
        if (oth != ed.othLast) { VLOG("edit: control hover %d -> %d", ed.othLast, oth); if (g_bar.tipSlot >= OtherTipBase) hideTip("control hover changed"); ed.othLast = oth; ed.othSince = GetTickCount(); if (oth >= 0) playHoverSound("picker control"); }
        if (oth >= 0 && g_bar.tipSlot != OtherTipBase + oth && GetTickCount() - ed.othSince >= TipDelayMs) showTipText(*ow[oth], otip[oth], OtherTipBase + oth, g_pickRect[1]);
    }

    // ---- picker contents (rebuilt from the HUD's group lists when stale)
    int maxOff = 0;
    if (ed.mode == M_Pick) {
        std::vector<Entry> all; unsigned h = 2166136261u;
        for (int g = 0; g < 6; ++g) {
            std::vector<Entry> es; readGroup(hud, g, &es);
            for (auto& x : es) {
                if (tabOf(x) != ed.tab || x.ref.empty()) continue;
                bool dup = false; for (auto& y : all) if (hb::Same(y.ref, x.ref)) dup = true;
                if (dup) continue;
                all.push_back(x); h = (h ^ (unsigned)x.key ^ ((unsigned)x.flags << 3)) * 16777619u;
            }
        }
        h = (h ^ (unsigned)ed.tab) * 16777619u;
        if (h != ed.sig || g_frame - ed.lastRefresh >= 60) {
            if (h != ed.sig) logf("edit: picker list tab=%s off=%d entries=%d (was %d) slot=%d", TabName[ed.tab], ed.off, (int)all.size(), (int)ed.list.size(), ed.slot);
            ed.sig = h; ed.lastRefresh = g_frame; ed.list = all;
        }
        maxOff = std::max(0, (int)ed.list.size() - CellCount);
        if (ed.off > maxOff) { VLOG("edit: scroll offset %d clamped to %d (entries=%d)", ed.off, maxOff, (int)ed.list.size()); ed.off = maxOff; }
        // wheel over the picker scrolls the list one entry per notch like the native quick-action buttons (wheel up = back toward the start)
        LONG acc = InterlockedExchange(&g_wheelAccum, 0);
        if (acc) {
            int steps = acc / 120; if (!steps) steps = acc > 0 ? 1 : -1;
            int no = std::max(0, std::min(maxOff, ed.off - steps));
            VLOG("edit: wheel acc=%ld steps=%d offset %d -> %d (max %d)", (long)acc, steps, ed.off, no, maxOff);
            scrollPicker(no, "wheel");
        }
        int n = (int)ed.list.size(), shown = std::min(n, CellCount);
        char t[112]; if (n == 0) snprintf(t, sizeof t, "Slot %c - %s: none available - Esc: back", slotDigit(ed.slot), TabName[ed.tab]);
        else snprintf(t, sizeof t, "Slot %c - %s %d-%d of %d - Esc: back", slotDigit(ed.slot), TabName[ed.tab], ed.off + 1, ed.off + shown, n);
        wText(g_bar.title, "title", ed.msg.empty() ? std::string(t) : ed.msg);
        for (int i = 0; i < TabCount; ++i) wFill(g_bar.tab[i], "tab", (i == ed.tab || oth == i) ? FrameHiResref : FrameResref);
        wFill(g_bar.prev, "prev", oth == 3 ? FrameHiResref : FrameResref); wFill(g_bar.next, "next", oth == 4 ? FrameHiResref : FrameResref); wFill(g_bar.clear, "clear", oth == 5 ? FrameHiResref : FrameResref);
        wAlpha(g_bar.prev, "prev", ed.off > 0 ? 1.0f : 0.4f); wAlpha(g_bar.next, "next", ed.off < maxOff ? 1.0f : 0.4f);
        for (int i = 0; i < CellCount; ++i) {
            Cell& c = g_bar.cell[i]; size_t idx = (size_t)ed.off + i;
            c.avail = idx < ed.list.size(); if (c.avail) c.entry = ed.list[idx];
            bool hov = ed.over == i && c.avail;
            wFill(c.bg, "cell.bg", hov ? FrameHiResref : FrameResref);
            wAlpha(c.bg, "cell.bg", c.avail ? 1.0f : EmptyFrameAlpha);
            wFill(c.ic, "cell.ic", c.avail ? c.entry.icon : std::string());
            wAlpha(c.ic, "cell.ic", (c.avail && !(c.entry.flags & 1)) ? DimAlpha : 1.0f);
        }
    } else if (ed.mode == M_Edit) {
        wText(g_bar.title, "title", ed.msg.empty() ? std::string("Click a slot to change it") : ed.msg);
    }

    // ---- picker hover (cells) + tooltip
    int over = -1;
    if (ed.mode == M_Pick && haveCur) for (int i = 0; i < CellCount && over < 0; ++i) if (g_bar.cell[i].avail && wHit(g_bar.cell[i].bg, pt)) over = i;
    if (over != ed.over) { VLOG("edit: cell hover %d -> %d", ed.over, over); if (g_bar.tipSlot >= CellTipBase && g_bar.tipSlot < ToggleTipId) hideTip("cell hover changed"); ed.over = over; ed.overStart = GetTickCount(); if (over >= 0) playHoverSound("picker cell"); }
    if (over >= 0 && g_bar.tipSlot != CellTipBase + over && GetTickCount() - ed.overStart >= TipDelayMs) showTipText(g_bar.cell[over].bg, buildTipText(0, g_bar.cell[over].entry), CellTipBase + over, g_pickRect[1]);

    // ---- toggle hover tooltip
    {
        bool ov = haveCur && wHit(g_bar.edit, pt);
        if (ov != ed.toggleWasOver) { VLOG("edit: toggle hover %d -> %d", (int)ed.toggleWasOver, (int)ov); ed.toggleWasOver = ov; ed.toggleSince = GetTickCount(); if (ov) playHoverSound("toggle"); if (!ov && g_bar.tipSlot == ToggleTipId) hideTip("left toggle"); }
        if (ov && g_bar.tipSlot != ToggleTipId && GetTickCount() - ed.toggleSince >= TipDelayMs) showTipText(g_bar.edit, ed.mode == M_Normal ? "Edit hotbar" : "Finish editing", ToggleTipId);
    }

    // ---- holding an arrow keeps scrolling (first repeat after 350 ms, then every 90 ms), like the native quick-action arrows
    if (ed.mode == M_Pick && haveCur) {
        int arrow = wHit(g_bar.prev, pt) ? -1 : (wHit(g_bar.next, pt) ? 1 : 0);
        if (!down || !arrow) ed.arrowHeld = 0;
        else if (click) { ed.arrowHeld = arrow; ed.arrowHeldSince = ed.arrowLastRep = GetTickCount(); }
        else if (arrow == ed.arrowHeld) {
            DWORD now = GetTickCount();
            if (now - ed.arrowHeldSince >= 350 && now - ed.arrowLastRep >= 90) { scrollPicker(std::max(0, std::min(maxOff, ed.off + arrow)), "arrow held"); ed.arrowLastRep = now; }
        }
    }

    // ---- clicks
    if (!click || !haveCur) return;
    if (wHit(g_bar.edit, pt)) { setMode(ed.mode == M_Normal ? M_Edit : M_Normal, -1, "toggle click"); return; }
    if (ed.mode == M_Normal) return;
    for (int s = 0; s < ButtonCount; ++s) if (wHit(g_bar.b[s].bg, pt)) { setMode(M_Pick, s, "slot click"); return; }
    if (ed.mode != M_Pick) return;
    for (int i = 0; i < TabCount; ++i) if (wHit(g_bar.tab[i], pt)) { logf("edit: tab click %d (%s)", i, TabName[i]); ed.tab = i; ed.off = 0; ed.sig = 0; ed.msg.clear(); return; }
    if (wHit(g_bar.prev, pt)) { if (ed.off > 0) scrollPicker(ed.off - 1, "prev click"); else logf("edit: prev click ignored (at start)"); return; }
    if (wHit(g_bar.next, pt)) { if (ed.off < maxOff) scrollPicker(ed.off + 1, "next click"); else logf("edit: next click ignored (at end)"); return; }
    if (wHit(g_bar.clear, pt)) { logf("edit: Clear click slot %d", ed.slot); if (assignSlot(hud, ed.slot, nullptr)) setMode(M_Edit, -1, "cleared"); return; }
    for (int i = 0; i < CellCount; ++i) if (wHit(g_bar.cell[i].bg, pt)) {
        if (!g_bar.cell[i].avail) { logf("edit: click on empty cell %d ignored", i); return; }
        Entry chosen = g_bar.cell[i].entry;
        logf("edit: cell %d click -> slot %d := group %d key=%08x %s \"%s\"", i, ed.slot, chosen.group, (unsigned)chosen.key, hb::Format(chosen.ref).c_str(), chosen.name.c_str());
        if (assignSlot(hud, ed.slot, &chosen)) setMode(M_Edit, -1, "assigned");
        return;
    }
    logf("edit: click at (%ld,%ld) in Pick mode hit nothing", (long)pt.x, (long)pt.y);
}

// Layout units -> px. With the projection flag cleared InitControl scales x by W/800 and y by H/600 (so 3840x1600 stretches x by 1.8).
// The HUD is drawn at a uniform H/600 px per unit, so x/width are squeezed by c = (H/600)/(W/800) afterwards.
struct Scale { double sx = 1.0, sy = 1.0, c = 1.0; };   // layout units -> px as InitControl scales (sx, sy), then the x squeeze c
Scale g_scale;
void aspectFix() {
    // NOT FnScreenInfo: FUN_0073FEA0 is a thiscall that reads [this+0x274]; calling it as cdecl passes a garbage/null ECX and crashed on load
    // (build 8, null read at 0x73FEAF). The window client size is what the engine renders at.
    short w = 0, h = 0; int rw = rdInt(GuiRefW, 0), rh = rdInt(GuiRefH, 0);
    HWND win = nullptr; EnumWindows(enumWnd, reinterpret_cast<LPARAM>(&win));
    RECT cr = {0, 0, 0, 0}; if (win) GetClientRect(win, &cr);
    w = (short)cr.right; h = (short)cr.bottom;
    double c = (w > 0 && h > 0 && rw > 0 && rh > 0) ? ((double)h / rh) / ((double)w / rw) : 1.0;
    if (c != 1.0) { g_scale.sx = (double)w / rw; g_scale.sy = (double)h / rh; g_scale.c = c; } else g_scale = Scale();
    logf("H3: window %p client=%dx%d ref=%dx%d -> x correction %.4f", (void*)win, (int)w, (int)h, rw, rh, c);
}
// ---- runtime-created controls + textures served from DLL memory (1.0.0; doc 07 "Phase R") ------------------------------------
// Labels: a native template struct of the open HUD layout initialises our label (InitControl with addToList=0 never touches the
// panel list), then we set our own id/rect/text/fill and append it to the panel list ourselves (draw order = list index).
constexpr uintptr_t FnPtrListAdd = 0x0083EA60;      // CExoArrayList<void*>::Add thiscall(list {ptr,count,cap}, value) RET 4
constexpr uintptr_t FnSetFont = 0x00416DE0;         // CSWGuiText::SetFont thiscall(text+0x18, const char resref[16]) RET 4
constexpr uintptr_t FnSetAlign = 0x00416FA0;        // CSWGuiText::SetAlignment thiscall(text+0x18, unsigned) RET 4
constexpr int IdSentinel = -31337;                  // InitControl's Load overwrites ctl+0x54; still the sentinel = template tag not in the layout
enum { TP_Plain = 0, TP_Panel = 1 };
const char* const TemplateTags[] = { "LBL_QUEUE1", "LBL_MOULDING3" };   // blank label / native framed panel, in every mipc28x6_p.gui
struct CtlSpec { const char* name; int tmpl; int x, y, w, h; const char* fill; const char* text; const char* font; int align; };
using PtrListAddFn = void(__thiscall*)(void*, void*);
using SetResFn = void(__thiscall*)(void*, const char*);
using SetUIntFn = void(__thiscall*)(void*, unsigned);

// Creates one label from its Layout[] spec and appends it to the panel's control list. Returns nullptr (label not in the list) on
// any failure; the caller then leaves that part of the bar/editor disabled.
unsigned char* createLabel(uintptr_t panel, const CtlSpec& sp, Widget* w) {
    unsigned char* ctl = static_cast<unsigned char*>(reinterpret_cast<NewFn>(FnNew)(LabelSize));
    if (!ctl) { logf("H3 %s: allocation failed", sp.name); return nullptr; }
    memset(ctl, 0, LabelSize);
    reinterpret_cast<LabelCtorFn>(FnLabelCtor)(ctl);
    uintptr_t c = reinterpret_cast<uintptr_t>(ctl);
    if (rdInt(c, 0) != (int)LabelVtable) { logf("H3 %s: ctor left vtable %08x (expected %08x), not created", sp.name, (unsigned)rdInt(c, 0), (unsigned)LabelVtable); return nullptr; }
    *reinterpret_cast<int*>(ctl + Ctl_Id) = IdSentinel;
    char exo[16] = {0};
    reinterpret_cast<CExoCtorFn>(FnExoCtor)(exo, TemplateTags[sp.tmpl]);
    reinterpret_cast<InitCtlFn>(FnInitControl)(reinterpret_cast<void*>(panel), ctl, exo, 0, 1);
    reinterpret_cast<CExoDtorFn>(FnExoDtor)(exo);
    if (rdInt(c, Ctl_Id) == IdSentinel) { logf("H3 %s: template %s not in the HUD layout, control not created", sp.name, TemplateTags[sp.tmpl]); return nullptr; }
    int index = rdInt(panel, Panel_CtlCount, -1);   // always appended: id == list index, so draw order follows Layout[]
    if (index < 0) { logf("H3 %s: panel control count unreadable, control not created", sp.name); return nullptr; }
    *reinterpret_cast<int*>(ctl + Ctl_Id) = index;
    const Scale& k = g_scale;
    int r[4] = { (int)((int)(sp.x * k.sx) * k.c + 0.5), (int)(sp.y * k.sy), (int)((int)(sp.w * k.sx) * k.c + 0.5), (int)(sp.h * k.sy) };
    reinterpret_cast<void(__thiscall*)(void*, int*)>((*reinterpret_cast<void***>(ctl))[1])(ctl, r);
    void* ts = ctl + Label_Text + Text_StringSub;
    if (sp.font) { char rr[16] = {0}; strncpy(rr, sp.font, sizeof rr); reinterpret_cast<SetResFn>(FnSetFont)(ts, rr); }
    if (sp.text) {
        char ex[16] = {0};
        reinterpret_cast<CExoCtorFn>(FnExoCtor)(ex, sp.text);
        reinterpret_cast<void(__thiscall*)(void*, void*)>(FnTextSet)(ts, ex);
        reinterpret_cast<CExoDtorFn>(FnExoDtor)(ex);
    }
    if (sp.align >= 0) reinterpret_cast<SetUIntFn>(FnSetAlign)(ts, (unsigned)sp.align);
    uintptr_t border = c + Label_Border;
    if (sp.fill) {
        if (rdInt(border, Border_Fill)) logf("H3 %s: template already has a fill, keeping it", sp.name);
        else *reinterpret_cast<void**>(border + Border_Fill) = imageFor(sp.fill);
    }
    int fl = rdInt(c, Ctl_Flags);
    // Hidden until the tick decides. Bit5 (0x20) makes the label's hit-test (0x00418D20) reject the mouse, so a hidden control never
    // swallows clicks; the tick clears it on shown frames/editor controls so clicks on the bar do not reach the world.
    *reinterpret_cast<int*>(ctl + Ctl_Flags) = (fl & ~2) | 0x20;
    reinterpret_cast<PtrListAddFn>(FnPtrListAdd)(reinterpret_cast<void*>(panel + Panel_CtlArray), ctl);
    int cnt = rdInt(panel, Panel_CtlCount, -1);
    if (cnt != index + 1 || rdInt(static_cast<uintptr_t>(rdInt(panel, Panel_CtlArray)), index * 4) != static_cast<int>(c)) {
        logf("H3 %s: append to the panel list failed (count %d -> %d), control not used", sp.name, index, cnt); return nullptr;
    }
    float ba = 1.0f; readAt(border, Border_Alpha, &ba);
    VLOG("H3 %s: created at index %d from %s rect=[%d,%d,%d,%d] fill=%s text=%s", sp.name, index, TemplateTags[sp.tmpl],
         rdInt(c, 4), rdInt(c, 8), rdInt(c, 0xC), rdInt(c, 0x10), sp.fill ? sp.fill : "-", sp.text ? sp.text : "-");
    w->ctl = ctl; w->baseAlpha = ba; w->visible = 0; w->why = "built";
    w->icon = sp.fill ? sp.fill : ""; w->text = sp.text ? sp.text : "";
    return ctl;
}

// All 57 controls in list (= draw) order, in 800x600 layout units. Offsets: see BgOff0..TipOff. align -1 / font nullptr / text nullptr
// keep the template's value (LBL_QUEUE1: white dialogfont16x16, align 9 = top-left; 17 = top-centre, 18 = centre).
const CtlSpec Layout[] = {
    { "LBL_HOTBARBG1",       TP_Plain,  29, 478,  35,  35, "fph_slot", nullptr,  nullptr,           -1 },
    { "LBL_HOTBARBG2",       TP_Plain,  69, 478,  35,  35, "fph_slot", nullptr,  nullptr,           -1 },
    { "LBL_HOTBARBG3",       TP_Plain, 109, 478,  35,  35, "fph_slot", nullptr,  nullptr,           -1 },
    { "LBL_HOTBARBG4",       TP_Plain, 149, 478,  35,  35, "fph_slot", nullptr,  nullptr,           -1 },
    { "LBL_HOTBARBG5",       TP_Plain, 189, 478,  35,  35, "fph_slot", nullptr,  nullptr,           -1 },
    { "LBL_HOTBARBG6",       TP_Plain, 229, 478,  35,  35, "fph_slot", nullptr,  nullptr,           -1 },
    { "LBL_HOTBARBG7",       TP_Plain, 269, 478,  35,  35, "fph_slot", nullptr,  nullptr,           -1 },
    { "LBL_HOTBARBG8",       TP_Plain, 309, 478,  35,  35, "fph_slot", nullptr,  nullptr,           -1 },
    { "LBL_HOTBARBG9",       TP_Plain, 349, 478,  35,  35, "fph_slot", nullptr,  nullptr,           -1 },
    { "LBL_HOTBARBG0",       TP_Plain, 389, 478,  35,  35, "fph_slot", nullptr,  nullptr,           -1 },
    { "LBL_HOTBAR1",         TP_Plain,  31, 480,  31,  31, nullptr,    nullptr,  nullptr,           -1 },
    { "LBL_HOTBAR2",         TP_Plain,  71, 480,  31,  31, nullptr,    nullptr,  nullptr,           -1 },
    { "LBL_HOTBAR3",         TP_Plain, 111, 480,  31,  31, nullptr,    nullptr,  nullptr,           -1 },
    { "LBL_HOTBAR4",         TP_Plain, 151, 480,  31,  31, nullptr,    nullptr,  nullptr,           -1 },
    { "LBL_HOTBAR5",         TP_Plain, 191, 480,  31,  31, nullptr,    nullptr,  nullptr,           -1 },
    { "LBL_HOTBAR6",         TP_Plain, 231, 480,  31,  31, nullptr,    nullptr,  nullptr,           -1 },
    { "LBL_HOTBAR7",         TP_Plain, 271, 480,  31,  31, nullptr,    nullptr,  nullptr,           -1 },
    { "LBL_HOTBAR8",         TP_Plain, 311, 480,  31,  31, nullptr,    nullptr,  nullptr,           -1 },
    { "LBL_HOTBAR9",         TP_Plain, 351, 480,  31,  31, nullptr,    nullptr,  nullptr,           -1 },
    { "LBL_HOTBAR0",         TP_Plain, 391, 480,  31,  31, nullptr,    nullptr,  nullptr,           -1 },
    { "LBL_HOTBAREDIT",      TP_Plain,   4, 478,  20,  35, "fph_edit", nullptr,  nullptr,           -1 },
    { "LBL_HOTBARPBG",       TP_Panel,   4, 360, 420, 112, nullptr,    nullptr,  nullptr,           -1 },
    { "LBL_HOTBARPTITLE",    TP_Plain,  12, 368, 404,  22, nullptr,    "",       "dialogfont10x10", 17 },
    { "LBL_HOTBARTAB0",      TP_Plain,  12, 394,  84,  24, "fph_slot", "Powers", "dialogfont10x10", 18 },
    { "LBL_HOTBARTAB1",      TP_Plain, 100, 394,  84,  24, "fph_slot", "Items",  "dialogfont10x10", 18 },
    { "LBL_HOTBARTAB2",      TP_Plain, 188, 394,  84,  24, "fph_slot", "Modes",  "dialogfont10x10", 18 },
    { "LBL_HOTBARPREV",      TP_Plain,  12, 426,  28,  35, "fph_slot", "<",      nullptr,           18 },
    { "LBL_HOTBARNEXT",      TP_Plain, 388, 426,  28,  35, "fph_slot", ">",      nullptr,           18 },
    { "LBL_HOTBARCLEAR",     TP_Plain, 346, 394,  70,  24, "fph_slot", "Clear",  "dialogfont10x10", 18 },
    { "LBL_HOTBARCELLBG0",   TP_Plain,  56, 426,  35,  35, "fph_slot", nullptr,  nullptr,           -1 },
    { "LBL_HOTBARCELLBG1",   TP_Plain,  96, 426,  35,  35, "fph_slot", nullptr,  nullptr,           -1 },
    { "LBL_HOTBARCELLBG2",   TP_Plain, 136, 426,  35,  35, "fph_slot", nullptr,  nullptr,           -1 },
    { "LBL_HOTBARCELLBG3",   TP_Plain, 176, 426,  35,  35, "fph_slot", nullptr,  nullptr,           -1 },
    { "LBL_HOTBARCELLBG4",   TP_Plain, 216, 426,  35,  35, "fph_slot", nullptr,  nullptr,           -1 },
    { "LBL_HOTBARCELLBG5",   TP_Plain, 256, 426,  35,  35, "fph_slot", nullptr,  nullptr,           -1 },
    { "LBL_HOTBARCELLBG6",   TP_Plain, 296, 426,  35,  35, "fph_slot", nullptr,  nullptr,           -1 },
    { "LBL_HOTBARCELLBG7",   TP_Plain, 336, 426,  35,  35, "fph_slot", nullptr,  nullptr,           -1 },
    { "LBL_HOTBARCELL0",     TP_Plain,  58, 428,  31,  31, nullptr,    nullptr,  nullptr,           -1 },
    { "LBL_HOTBARCELL1",     TP_Plain,  98, 428,  31,  31, nullptr,    nullptr,  nullptr,           -1 },
    { "LBL_HOTBARCELL2",     TP_Plain, 138, 428,  31,  31, nullptr,    nullptr,  nullptr,           -1 },
    { "LBL_HOTBARCELL3",     TP_Plain, 178, 428,  31,  31, nullptr,    nullptr,  nullptr,           -1 },
    { "LBL_HOTBARCELL4",     TP_Plain, 218, 428,  31,  31, nullptr,    nullptr,  nullptr,           -1 },
    { "LBL_HOTBARCELL5",     TP_Plain, 258, 428,  31,  31, nullptr,    nullptr,  nullptr,           -1 },
    { "LBL_HOTBARCELL6",     TP_Plain, 298, 428,  31,  31, nullptr,    nullptr,  nullptr,           -1 },
    { "LBL_HOTBARCELL7",     TP_Plain, 338, 428,  31,  31, nullptr,    nullptr,  nullptr,           -1 },
    { "LBL_HOTBARNUM1",      TP_Plain,  33, 479,  18,  18, nullptr,    "1",      nullptr,            9 },
    { "LBL_HOTBARNUM2",      TP_Plain,  73, 479,  18,  18, nullptr,    "2",      nullptr,            9 },
    { "LBL_HOTBARNUM3",      TP_Plain, 113, 479,  18,  18, nullptr,    "3",      nullptr,            9 },
    { "LBL_HOTBARNUM4",      TP_Plain, 153, 479,  18,  18, nullptr,    "4",      nullptr,            9 },
    { "LBL_HOTBARNUM5",      TP_Plain, 193, 479,  18,  18, nullptr,    "5",      nullptr,            9 },
    { "LBL_HOTBARNUM6",      TP_Plain, 233, 479,  18,  18, nullptr,    "6",      nullptr,            9 },
    { "LBL_HOTBARNUM7",      TP_Plain, 273, 479,  18,  18, nullptr,    "7",      nullptr,            9 },
    { "LBL_HOTBARNUM8",      TP_Plain, 313, 479,  18,  18, nullptr,    "8",      nullptr,            9 },
    { "LBL_HOTBARNUM9",      TP_Plain, 353, 479,  18,  18, nullptr,    "9",      nullptr,            9 },
    { "LBL_HOTBARNUM0",      TP_Plain, 393, 479,  18,  18, nullptr,    "0",      nullptr,            9 },
    { "LBL_HOTBARTIPBG",     TP_Panel,  12, 380, 300,  90, nullptr,    nullptr,  nullptr,           -1 },
    { "LBL_HOTBARTIP",       TP_Plain,  12, 380, 300,  90, nullptr,    "",       nullptr,           18 },
};
static_assert(sizeof Layout / sizeof Layout[0] == ControlCount, "Layout[] must list every control in offset order");

Widget* widgetFor(Bar& bar, int off) {
    if (off < IcOff0) return &bar.b[off - BgOff0].bg;
    if (off < EditOff) return &bar.b[off - IcOff0].ic;
    if (off == EditOff) return &bar.edit;
    if (off == PbgOff) return &bar.pbg;
    if (off == TitleOff) return &bar.title;
    if (off < PrevOff) return &bar.tab[off - TabOff0];
    if (off == PrevOff) return &bar.prev;
    if (off == NextOff) return &bar.next;
    if (off == ClearOff) return &bar.clear;
    if (off < CellIcOff0) return &bar.cell[off - CellBgOff0].bg;
    if (off < NumOff0) return &bar.cell[off - CellIcOff0].ic;
    if (off < TipBgOff) return &bar.b[off - NumOff0].num;
    return off == TipBgOff ? &bar.tipBg : &bar.tip;
}

// Textures: a CAurTextureBasic registered under our name (like the engine's own "NormCubeMap") with the decoded pixels already in place
// and +0xE4 "constructed" set, so the engine never asks the resource manager for it; the texture tick uploads it and frees the buffer.
constexpr uintptr_t FnTexBasicCtor = 0x00423000;    // CAurTextureBasic ctor thiscall(this 0xF4 B, name, name) RET 8; registers the name globally
constexpr uintptr_t FnEngineMalloc = 0x0091D288;    // engine operator new[]: FreeImage (0x00421C40) releases +0x44 with delete[] when +0xE7 == 0
constexpr uintptr_t FnTexListAdd = 0x004491C0, TexPendingList = 0x00A1BC2C;   // pending-build list, consumed by the texture tick
constexpr uintptr_t FnTexReset = 0x00423990;        // CAurTextureBasic::Reset fastcall(basic)
constexpr int TexBasicSize = 0xF4;
constexpr int Tex_Pixels = 0x44, Tex_MipBytes = 0x5C, Tex_W = 0x68, Tex_H = 0x6C, Tex_Bpp = 0x74, Tex_Format = 0x78;
constexpr int Tex_Cube = 0xDF, Tex_Constructed = 0xE4, Tex_Missing = 0xE5, Tex_FromRes = 0xE7, Tex_Tpc = 0xE9;
constexpr int TexCount = sizeof EmbeddedTextures / sizeof EmbeddedTextures[0];
struct EmbTex { unsigned char* basic = nullptr; int w = 0, h = 0, heals = 0; };
EmbTex g_tex[TexCount]; bool g_texInit = false;

bool fillTexture(int i, const char* why) {
    const EmbeddedTexture& src = EmbeddedTextures[i]; EmbTex& t = g_tex[i]; const unsigned char* d = src.data;
    if (src.size < 18 || d[1] != 0 || d[2] != 2 || d[16] != 32) { logf("tex %s: embedded TGA not uncompressed 32-bit, skipped", src.resref); return false; }
    int w = d[12] | d[13] << 8, h = d[14] | d[15] << 8; unsigned off = 18u + d[0], n = (unsigned)w * h * 4;
    if (w <= 0 || h <= 0 || off + n > src.size) { logf("tex %s: embedded TGA truncated (%dx%d, %u bytes)", src.resref, w, h, src.size); return false; }
    unsigned char* px = static_cast<unsigned char*>(reinterpret_cast<NewFn>(FnEngineMalloc)(n));
    if (!px) { logf("tex %s: engine malloc(%u) failed", src.resref, n); return false; }
    for (unsigned j = 0; j < n; j += 4) { px[j] = d[off + j + 2]; px[j + 1] = d[off + j + 1]; px[j + 2] = d[off + j]; px[j + 3] = d[off + j + 3]; }   // BGRA -> RGBA, rows as stored (= CResTGA)
    unsigned char* b = t.basic;
    *reinterpret_cast<unsigned char**>(b + Tex_Pixels) = px;
    *reinterpret_cast<int*>(b + Tex_W) = w; *reinterpret_cast<int*>(b + Tex_H) = h; *reinterpret_cast<int*>(b + Tex_Bpp) = 4;
    *reinterpret_cast<int*>(b + Tex_Format) = 0; *reinterpret_cast<int*>(b + Tex_MipBytes) = 0;
    b[Tex_Cube] = 0; b[Tex_FromRes] = 0; b[Tex_Tpc] = 0; b[Tex_Missing] = 0; b[Tex_Constructed] = 1;
    reinterpret_cast<PtrListAddFn>(FnTexListAdd)(reinterpret_cast<void*>(TexPendingList), b);
    t.w = w; t.h = h;
    logf("tex %s: %s, %dx%d RGBA queued for upload (basic %p, pending %d)", src.resref, why, w, h, (void*)b, rdInt(TexPendingList, 4));
    return true;
}
void ensureTextures() {   // once per process; the textures outlive every HUD (never freed)
    if (g_texInit) return;
    g_texInit = true;
    for (int i = 0; i < TexCount; ++i) {
        unsigned char* b = static_cast<unsigned char*>(reinterpret_cast<NewFn>(FnNew)(TexBasicSize));
        if (!b) { logf("tex %s: allocation failed", EmbeddedTextures[i].resref); continue; }
        memset(b, 0, TexBasicSize);
        reinterpret_cast<void*(__thiscall*)(void*, const char*, const char*)>(FnTexBasicCtor)(b, EmbeddedTextures[i].resref, EmbeddedTextures[i].resref);
        g_tex[i].basic = b;
        if (fillTexture(i, "created")) imageFor(EmbeddedTextures[i].resref);   // a pooled GUI handle that is never released keeps the texture alive
    }
}
void logTextures(const char* when) {
    for (int i = 0; i < TexCount; ++i) if (unsigned char* b = g_tex[i].basic)
        logf("tex %s (%s): gl=%u constructed=%d missing=%d pixels=%p %dx%d", EmbeddedTextures[i].resref, when, (unsigned)rdInt(reinterpret_cast<uintptr_t>(b), 0x58),
             (int)b[Tex_Constructed], (int)b[Tex_Missing], *reinterpret_cast<void**>(b + Tex_Pixels), *reinterpret_cast<int*>(b + Tex_W), *reinterpret_cast<int*>(b + Tex_H));
}
// A GL reset (ResetAll 0x00427D90 / SetMem 0x00427DE0) Resets every registered texture (+0xE4 = 0, pixels and GL names freed) and
// re-queues all of them on the work list. If we see it first, refill (the duplicate list entry is a no-op: +0xE4 = 1, +0x44 = NULL after
// the first build). If the engine rebuilt first, its resource lookup missed our name (+0xE5 = 1): Reset and refill. DB lesson 290.
void healTextures() {
    for (int i = 0; i < TexCount; ++i) {
        EmbTex& t = g_tex[i]; unsigned char* b = t.basic;
        if (!b) continue;
        bool built = b[Tex_Constructed] != 0; void* px = *reinterpret_cast<void**>(b + Tex_Pixels); int w = *reinterpret_cast<int*>(b + Tex_W);
        if (built && !px && !b[Tex_Missing] && rdInt(reinterpret_cast<uintptr_t>(b), 0x58)) { t.heals = 0; continue; }   // uploaded: healthy
        if (t.heals >= 20) continue;   // give up after 20 consecutive failed refills (art missing, labels still work)
        if (!built && !px) { ++t.heals; fillTexture(i, "refilled after a texture reset"); }
        else if (built && !px && (b[Tex_Missing] || w != t.w)) {
            ++t.heals; logf("tex %s: rebuilt without our pixels (missing=%d w=%d), resetting", EmbeddedTextures[i].resref, (int)b[Tex_Missing], w);
            reinterpret_cast<void(__fastcall*)(void*)>(FnTexReset)(b);
            fillTexture(i, "refilled after a missing rebuild");
        }
    }
}

} // namespace

// ---- hook 1: keyboard capture -------------------------------------------------------------------------
struct DIRecord { DWORD dwOfs, dwData; };

extern "C" void __cdecl CaptureHotbarKey(DIRecord* rec, int dev) {
    if (!rec) return;
    if (dev != g_kbDevice) return;
    DWORD dik = rec->dwOfs; bool down = (rec->dwData & 0x80) != 0;
    bool isMod = true;
    switch (dik) {
    case 0x1D: case 0x9D: g_ctrl = down; break;
    case 0x38: case 0xB8: g_alt = down; break;
    case 0x2A: case 0x36: g_shift = down; break;
    default: isMod = false;
    }
    bool isDigit = dik >= 0x02 && dik <= 0x0B, isEsc = dik == 0x01;
    if (isDigit && down) {   // resync modifiers that missed their key-up (Alt-Tab, modal): only ever CLEAR a stuck flag
        bool c = (GetAsyncKeyState(VK_CONTROL) & 0x8000) != 0, a = (GetAsyncKeyState(VK_MENU) & 0x8000) != 0, sh = (GetAsyncKeyState(VK_SHIFT) & 0x8000) != 0;
        if ((g_ctrl && !c) || (g_alt && !a) || (g_shift && !sh)) { logf("cap: stuck modifier cleared (ctrl %d->%d alt %d->%d shift %d->%d)", (int)g_ctrl, (int)(g_ctrl && c), (int)g_alt, (int)(g_alt && a), (int)g_shift, (int)(g_shift && sh)); g_ctrl = g_ctrl && c; g_alt = g_alt && a; g_shift = g_shift && sh; }
    }
    const char* decision = "pass";
    if (isEsc) {   // while the editor is open Esc backs out of it instead of opening the game menu
        if (!down) { if (g_downSwallowed[dik]) { g_downSwallowed[dik] = false; rec->dwOfs = 0; rec->dwData = 0; decision = "swallow-up (edit)"; } }
        else if (g_editOpen && g_hudGateOk && (GetTickCount() - g_hudTick) < 250) { g_downSwallowed[dik] = true; g_escHit = true; rec->dwOfs = 0; rec->dwData = 0; decision = "SWALLOW (edit Esc)"; }
        else decision = "pass(edit closed)";
    }
    if (isDigit) {
        if (!down) {
            if (g_downSwallowed[dik]) { g_downSwallowed[dik] = false; rec->dwOfs = 0; rec->dwData = 0; decision = "swallow-up"; }
        } else if (!g_shift) {
            int slot = (int)dik - hb::kFirstDik;
            bool active = g_hudGateOk && (GetTickCount() - g_hudTick) < 250;
            if (g_ctrl || g_alt) decision = "pass(ctrl/alt)";   // only plain digits are ours; Ctrl/Alt+digit stay the game's
            else if (!active) decision = "pass(hud inactive)";
            else if (g_editOpen) decision = "pass(edit mode: never invoke)";
            else if (!g_slotBound[slot]) decision = "pass(unbound)";
            else {
                int next = (g_ringHead + 1) % 16;   // a bound key is ALWAYS swallowed: passing it on would switch party members (keys 1-3)
                g_downSwallowed[dik] = true; rec->dwOfs = 0; rec->dwData = 0;
                if (next == g_ringTail) decision = "SWALLOW(ring full, request dropped)";
                else { g_ring[g_ringHead] = { slot }; g_ringHead = next; decision = "SWALLOW"; }
            }
        } else decision = "pass(shift)";
    }
    if (isDigit || isMod || isEsc) { VLOG("cap: dev=%d dik=%02x %s mods=%c%c%c -> %s", dev, (unsigned)dik, down ? "down" : "up", g_ctrl ? 'C' : '-', g_alt ? 'A' : '-', g_shift ? 'S' : '-', decision); }
}

// ---- hook 3: HUD constructor -- build the button labels ---------------------------------------------------
// Runs inside CSWGuiMainInterface's constructor between the last InitControl and StopLoadFromLayout, so the layout GFF
// (panel+0x30) is still open: createLabel copies native template controls from it. All native controls are bound by now.
extern "C" void __cdecl HotbarBuildButtons(int panelArg) {
    uintptr_t panel = static_cast<uintptr_t>(panelArg);
    int before = rdInt(panel, Panel_CtlCount, -1);
    logf("H3 build: panel=%08x vtable=%08x controls=%d gff=%08x (previous bar panel=%08x built=%d)", (unsigned)panel, (unsigned)rdInt(panel, 0), before, (unsigned)rdInt(panel, 0x30), (unsigned)g_bar.panel, g_bar.built);
    if (!panel || IsBadReadPtr(reinterpret_cast<void*>(panel), 0x40)) { logf("H3: panel null/unreadable, abort"); return; }
    if (g_bar.panel) logf("H3: replacing bar of old HUD %08x (its labels stay leaked, never freed)", (unsigned)g_bar.panel);
    g_bar = Bar(); g_bar.panel = panel;
    // InitControl (0x0040F620) applies a non-linear aspect projection to the extent while the global at 0x00A1B9F0 is nonzero (live build 3:
    // slots 8 and 0 came out 964 px wide). The ctor clears it right after this hook (0x0074850D), so clear it for our binds and restore.
    int* projFlag = reinterpret_cast<int*>(ProjectionFlag);
    int savedFlag = IsBadReadPtr(projFlag, 4) ? 0 : *projFlag;
    logf("H3: projection flag %08x = %d (cleared for the binds, restored after)", (unsigned)ProjectionFlag, savedFlag);
    if (savedFlag && !IsBadWritePtr(projFlag, 4)) *projFlag = 0;
    aspectFix();
    ensureTextures();
    // Every control is created from Layout[] and appended after the native ones (ids base..base+56). A control that fails stays
    // nullptr: its slot part / the editor / the tooltip is then disabled, everything else still works.
    int created = 0;
    for (int i = 0; i < ControlCount; ++i) created += createLabel(panel, Layout[i], widgetFor(g_bar, i)) != nullptr;
    int built = 0, eb = 0;
    for (int s = 0; s < ButtonCount; ++s) if (g_bar.b[s].bg.ctl || g_bar.b[s].ic.ctl) ++built;
    for (int i = EditOff; i < EditOff + EditorControlCount; ++i) eb += widgetFor(g_bar, i)->ctl != nullptr;
    g_editOpen = false; g_escHit = false; g_pickRect[2] = 0; g_wheelAccum = 0;   // editor state is per HUD instance
    g_bar.editBound = (eb == EditorControlCount) ? 1 : 0;   // a partial editor UI would be confusing: all or nothing
    if (g_bar.pbg.ctl) for (int i = 0; i < 4; ++i) g_bar.ed.pbgRect[i] = rdInt(reinterpret_cast<uintptr_t>(g_bar.pbg.ctl), 4 + 4 * i);
    if (savedFlag && !IsBadWritePtr(projFlag, 4)) *projFlag = savedFlag;
    g_bar.built = built;
    int after = rdInt(panel, Panel_CtlCount, -1);
    logf("H3: %d controls created at runtime (indices %d..%d), %d/%d buttons, editor controls %d/%d -> editor %s, picker background rect [%d,%d,%d,%d]",
         created, before, after - 1, built, ButtonCount, eb, EditorControlCount, g_bar.editBound ? "ENABLED" : "DISABLED",
         g_bar.ed.pbgRect[0], g_bar.ed.pbgRect[1], g_bar.ed.pbgRect[2], g_bar.ed.pbgRect[3]);
    if (created != ControlCount) logf("H3: WARNING %d of %d controls NOT created (see the lines above)", ControlCount - created, ControlCount);
}

// ---- hook 2: HUD tick ---------------------------------------------------------------------------------
extern "C" void __cdecl HotbarHudTick(void* hudPtr) {
    uintptr_t hud = reinterpret_cast<uintptr_t>(hudPtr);
    ++g_frame; g_frameForLog = g_frame;
    static DWORD lastTickTime = 0; DWORD nowT = GetTickCount();
    if (lastTickTime && nowT - lastTickTime > 1500) logf("tick: gap of %lu ms since previous HUD tick (load/menu/HUD destroyed?)", (unsigned long)(nowT - lastTickTime));
    lastTickTime = nowT;
    if (g_frame % 1800 == 0) logf("heartbeat: frame=%ld bar(panel=%08x built=%d vis=%d%d%d%d%d%d%d%d%d%d) gate=%d char='%s' ring=%d cfgMtime=%lld invoke=%d", g_frame, (unsigned)g_bar.panel, g_bar.built, g_bar.b[0].ic.visible, g_bar.b[1].ic.visible, g_bar.b[2].ic.visible, g_bar.b[3].ic.visible, g_bar.b[4].ic.visible, g_bar.b[5].ic.visible, g_bar.b[6].ic.visible, g_bar.b[7].ic.visible, g_bar.b[8].ic.visible, g_bar.b[9].ic.visible, (int)g_hudGateOk, g_charKey.c_str(), (g_ringHead - g_ringTail + 16) % 16, g_cfgMtime, g_cfg.general.invoke);
    if (g_frame == 1) logf("tick: first HUD tick hud=%08x kbdev=%d", (unsigned)hud, g_kbDevice);
    if (hud != g_hud) { g_hud = hud; logf("tick: hud pointer now %08x", (unsigned)hud); }
    if (!hud || IsBadReadPtr(hudPtr, 0x1CA0)) { if (g_hudGateOk) logf("tick: hud %08x unreadable -> gate off", (unsigned)hud); g_hudGateOk = false; return; }

    checkConfig(g_frame == 1);
    healTextures();
    if (g_frame == 120) logTextures("frame 120");

    static bool lastGate = false; static const char* lastWhy = nullptr;
    bool gate = gameplayHudActive(hud);
    g_hudGateOk = gate; g_hudTick = GetTickCount();
    if (gate != lastGate || lastWhy != gateWhy) { lastGate = gate; lastWhy = gateWhy; logf("gate: %s (%s)", gate ? "ACTIVE" : "inactive", gateWhy); if (!gate) logPanels(hud); }

    bool charChanged = false;
    {   // every frame: the bar must follow the controlled character without a visible lag
        static uintptr_t lastCreature = ~0u; static unsigned lastOid = 0xFFFFFFF0u;
        uintptr_t cr = controlledCreature(); unsigned oid = cr ? (unsigned)rdInt(cr, 4) : 0;
        static int lastParty = -1; bool same = (cr == lastCreature && oid == lastOid && g_partyCount == lastParty); lastParty = g_partyCount;   // unchanged creature: skip the key build (string work) entirely
        lastCreature = cr; lastOid = oid;
        std::string k = same ? g_charKey : computeCharacterKey();
        if (k != g_charKey) { logf("character: '%s' -> '%s'", g_charKey.c_str(), k.c_str()); g_charKey = k; g_charChangeTick = GetTickCount(); recomputeBound(); charChanged = true; }
    }
    if (charChanged || g_frame % ButtonRefreshFrames == 1 || g_frame == 2) refreshEffective(hud);
    updateButtons(hud, gate);
    updateHover(gate);
    updateEditor(hud, gate);
    if (gate) drainRing(hud);
    else if (g_ringTail != g_ringHead) { logf("tick: gate closed, discarding %d queued request(s)", (g_ringHead - g_ringTail + 16) % 16); g_ringTail = g_ringHead; }   // never invoke while the HUD is not the active panel
}

BOOL WINAPI DllMain(HINSTANCE, DWORD reason, LPVOID) {
    if (reason == DLL_PROCESS_DETACH && g_oldProc && g_gameWnd && IsWindow(g_gameWnd) &&
        reinterpret_cast<WNDPROC>(GetWindowLongPtrA(g_gameWnd, GWLP_WNDPROC)) == wheelProc) {
        SetWindowLongPtrA(g_gameWnd, GWLP_WNDPROC, reinterpret_cast<LONG_PTR>(g_oldProc)); g_oldProc = nullptr;   // only if we are still on top (Mod 1/5 do the same)
    }
    if (reason == DLL_PROCESS_ATTACH) {
        DeleteFileA(LogPrevPath); MoveFileA(LogPath, LogPrevPath);   // rotate BEFORE the first logf (the logger reopens per line, nothing is held open)
        char cwd[MAX_PATH] = "?"; GetCurrentDirectoryA(MAX_PATH, cwd);
        logf("force-power-hotbar 1.0.0 loaded; cwd=%s pid=%lu ini=%s", cwd, (unsigned long)GetCurrentProcessId(), IniPath);
        logf("addresses: invoke=%08x kbdevGlobal=%08x app=%08x getCreature=%08x whitelist=%08x,%08x,%08x,%08x", (unsigned)HudInvokeGroup, (unsigned)KeyboardDeviceGlobal, (unsigned)AppGlobal, (unsigned)GetControlledCreature, (unsigned)PanelWhitelist[0], (unsigned)PanelWhitelist[1], (unsigned)PanelWhitelist[2], (unsigned)PanelWhitelist[3]);
    }
    return TRUE;
}
