// Level-Up Override 0.3.0-a (Steam Aspyr build 6A522E71...). Makes the engine's AUTO level-up follow a per-character build
// preset, can HOLD a creature's level-up until a class change (hold mode) and can make level-ups instant (opt-in). Config from ini only
// (no UI / save binding yet). Default mode=log only logs + dry-runs.
// History: 0.1.0-probe log + dry run; 0.1.1 creature feat lists read from +0x00/+0x18; 0.2.0 applyRewrite + APPLIED/AFTER dump;
// 0.2.1 rewrite only under AutoLevelup (user requirement: pre-determine the auto level-up, never override manual picks);
// 0.3.0-a table v2 (presets + class levels), levelNow (hold rule v2), per-tag config (preset./instant./hold.), Class Skill feats in the
// unspent recomputation, hold gate (13 CanLevelUp sites), instant gate (4 options-accessor sites), GUI guards + Auto OK backstop.
// Investigation/design: patch_manager_mods/08_level_up_override.md (local-setup/KOTOR-II worktree), plan research/companion_levelup/PHASE4_PLAN.md.
//
// Hook 1: detour at CSWSCreatureStats::LevelUp 0x006B9870 entry (thiscall: ECX = stats, [esp+4] = pending*, [esp+8] = addToList,
// [esp+0] = return address; EBP = the caller's frame because our code runs BEFORE the original `push ebp`). Every level-up path ends
// there (manual GUI message, Auto button, Auto Level Up NPCs, XP award, SetExperience replay of stored structs, LevelUpHenchman).
// This hook can NEVER veto (AutoLevelup would spin forever): a HOLD decision inside it is logged HOLD_MIDLOOP and treated as vanilla.
//
// Per call (mode log|rewrite): dump the creature (tag, classes, XP, unspent, skill ranks, feat list) and the 0x30-byte pending struct
// (class, ability, HP, force, unspent, skill deltas, feats, spells add/remove, raw hex) plus the caller chain mapped to a flow name, to
// levelup_override_log.txt in the game dir. For tags configured with a preset in the runtime table (levelup_paths.ini, generated by
// research/companion_levelup/gen_runtime_table.py) also print the DECIDE line and the dry-run "DRY ..." line;
// research/companion_levelup/simulate_rewrite.py prints the identical DRY line for the same inputs (computeRewrite == compute_rewrite).
//
// Hooks 2-5 (all 5-byte `E8 rel32` call sites, replaced; the handler's return value is EAX):
//   hold gate    CanLevelUp 0x6B9790 at 13 sites: result forced to 0 while levelNow()==HOLD (mode=rewrite; mode=log logs WOULD HOLD)
//   instant gate options accessor 0x72FB00 at 4 sites: returns a copy of the options with bit0 of +8 set (instant.<tag>=1, not held)
//   GUI guards   GetCharacterChangeInProgress 0x740FC0 at 0x84FD2F / 0x84F9FE: nonzero for a held leader (button/hotkey/confirm box)
//   Auto OK      0x77D800 at 0x850062: returns 0 for a held leader so DoAutoLevelup skips AutoLevelup
// All handlers pass through to the real function on any unreadable pointer, for the PC (empty tag) and for unconfigured tags.
//
// Config levelup_override.ini (game dir, re-read when its mtime changes, stat at most once per second from the gates; missing = defaults):
//   mode=log (default) | rewrite (apply DRY result / hold / instant for configured tags) | off
//   preset.<tag>=<preset id>   instant.<tag>=0|1 (default 0)   hold.<tag>=0|1 (default 1)      (dev keys; M3 adds a per-playthrough source)
//   tags=atton,kreia   legacy: each tag without a preset key gets preset <tag>__live, instant 0, hold 0 (0.2.1 behaviour)
//   verbose=1 (0 = one summary line per call)   apply=1 (default)  second kill switch: mode=rewrite + apply=0 = dry run (WOULD REWRITE)
//   table=levelup_paths.ini
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stdio.h>
#include <string.h>
#include <stdarg.h>
#include <stdlib.h>
#include <stdint.h>
#include "../_shared/SafeRead.h"

namespace {

using saferead::readAt;
using saferead::probeRead;

constexpr const char* Version = "0.3.0-a";
constexpr bool ApplyEnabled = true;    // build-level switch; runtime switches are mode=rewrite + apply=1 + tags=

// ---- engine layout (doc 08 "Struct offsets" + "Phase 1b results" O5) ------------------------------------
constexpr uintptr_t RulesGlobal = 0x00A1B4D0;      // rules singleton; +0x123 byte skill count
constexpr int Rules_SkillCount = 0x123;
constexpr int St_Creature = 0x24, St_FeatList = 0x00, St_FeatList2 = 0x18, St_XP = 0x68, St_ClassCount = 0x8D,
              St_ClassId = 0xAB, St_ClassLevel = 0xAC, St_ClassNeg = 0xAD, St_ClassStride = 0x28, St_Unspent = 0x170,
              St_SkillRanks = 0x174;
constexpr int Cr_Tag = 0x18;                       // CExoString {char*, len}
constexpr int Pd_SpellsAdd = 0x00, Pd_SpellsRem = 0x0C, Pd_Feats = 0x18, Pd_Deltas = 0x24, Pd_Unspent = 0x28,
              Pd_Ability = 0x2A, Pd_HP = 0x2B, Pd_Class = 0x2C, Pd_Force = 0x2D, Pd_Size = 0x30;

// ---- caller map (steam_functions.tsv sizes) --------------------------------------------------------------
struct Fn { uintptr_t lo; unsigned size; const char* name; const char* flow; };
const Fn kFns[] = {
    {0x006B9640, 334, "ValidateLevelUp", nullptr},
    {0x006B6BD0, 1167, "SetExperience", "setexp-stored"},
    {0x00661C30, 1059, "HandleLevelUpMsg", "manual-gui"},
    {0x006BEDF0, 5244, "AutoLevelup", nullptr},
    {0x00850010, 124, "DoAutoLevelup", "auto-button"},
    {0x0084FE20, 490, "StartAutoLevelup", "auto-button"},
    {0x005FEDD0, 135, "AutoLevelUpNPCs", "auto-npcs"},
    {0x005FE0C0, 737, "DistributeExperience", "distribute-xp"},
    {0x005FD480, 911, "XPAwardTail", "xp-award"},
    {0x0074EE90, 2732, "PortraitRefresh", "portrait-refresh"},
    {0x0066C7A0, 483, "LevelUpHenchman", "levelup-henchman"},
    {0x008F8070, 579, "BeginPlayGame", "manual-gui"},
};
const Fn* findFn(uintptr_t a) {
    for (const Fn& f : kFns) if (a >= f.lo && a < f.lo + f.size) return &f;
    return nullptr;
}

// ---- engine-granted power ids kept on rewrite (O3: AddGrantedPowers 0x847A70) ----------------------------
bool isEngineGrantPower(uint32_t s) {
    return (s >= 0x90 && s <= 0x94) || (s >= 0x9C && s <= 0x9E) || (s >= 0xA4 && s <= 0xAB) ||
           (s >= 0x102 && s <= 0x104) || s == 0x109;
}

// ---- logging -------------------------------------------------------------------------------------------
constexpr int MaxLogLines = 20000;
constexpr long RotateBytes = 4L << 20;
const char* LogName = "levelup_override_log.txt";
int g_logLines = 0;
FILE* g_f = nullptr;   // open only inside one hook call

bool logOpen() {
    if (g_logLines >= MaxLogLines) return false;
    g_f = fopen(LogName, "a");
    return g_f != nullptr;
}
void logClose() { if (g_f) { fclose(g_f); g_f = nullptr; } }
void logf(const char* fmt, ...) {
    if (!g_f || g_logLines >= MaxLogLines) return;
    ++g_logLines;
    va_list ap; va_start(ap, fmt); vfprintf(g_f, fmt, ap); va_end(ap);
    fputc('\n', g_f);
    if (g_logLines == MaxLogLines) fputs("== log line cap reached ==\n", g_f);
}
// Opens, writes one line, closes (for config/table messages outside a call dump).
void logLine(const char* fmt, ...) {
    bool own = !g_f;
    if (own && !logOpen()) return;
    ++g_logLines;
    fprintf(g_f, "[%lu] ", GetTickCount());
    va_list ap; va_start(ap, fmt); vfprintf(g_f, fmt, ap); va_end(ap);
    fputc('\n', g_f);
    if (own) logClose();
}

// Small appender for building one log line from lists.
struct Buf {
    char s[2048]; int n = 0;
    Buf() { s[0] = 0; }
    void add(const char* fmt, ...) {
        if (n >= (int)sizeof s - 1) return;
        va_list ap; va_start(ap, fmt);
        int w = vsnprintf(s + n, sizeof s - n, fmt, ap);
        va_end(ap);
        if (w > 0) n = (n + w < (int)sizeof s) ? n + w : (int)sizeof s - 1;
    }
};

// ---- config (levelup_override.ini) ------------------------------------------------------------------------
enum class Mode { Off, Log, Rewrite };
constexpr int MaxTagCfg = 16;
constexpr DWORD ReloadThrottleMs = 1000;
// Per-tag configuration as the gates see it. `preset` = index into g_presets (-1 = unresolved / table not loaded).
struct TagCfg {
    char tag[32];
    int preset;
    bool instant, hold;
};
struct Config {
    Mode mode = Mode::Log;
    bool verbose = true;
    bool apply = true;
    char table[MAX_PATH] = "levelup_paths.ini";
    TagCfg tags[MaxTagCfg] = {};
    char presetId[MaxTagCfg][48] = {};   // requested preset id per tag (resolved against the table by resolvePresets)
    int nTags = 0;
};
Config g_cfg;
uint64_t g_cfgStamp = ~0ULL;   // forces the first read
DWORD g_cfgLast = 0, g_tableLast = 0;
bool g_cfgChecked = false, g_tableChecked = false;

uint64_t fileStamp(const char* path) {   // 0 = missing
    WIN32_FILE_ATTRIBUTE_DATA d;
    if (!GetFileAttributesExA(path, GetFileExInfoStandard, &d)) return 0;
    return (static_cast<uint64_t>(d.ftLastWriteTime.dwHighDateTime) << 32 | d.ftLastWriteTime.dwLowDateTime) ^ d.nFileSizeLow;
}

// True when a file check is due: always on the first call and when forced, else at most once per ReloadThrottleMs.
bool reloadDue(DWORD* last, bool* checked, bool force) {
    DWORD now = GetTickCount();
    if (*checked && !force && now - *last < ReloadThrottleMs) return false;
    *last = now; *checked = true;
    return true;
}

char* trim(char* s) {
    while (*s == ' ' || *s == '\t') ++s;
    char* e = s + strlen(s);
    while (e > s && (e[-1] == ' ' || e[-1] == '\t' || e[-1] == '\r' || e[-1] == '\n')) *--e = 0;
    return s;
}
void lower(char* s) { for (; *s; ++s) if (*s >= 'A' && *s <= 'Z') *s += 32; }

void resolvePresets();   // below (needs the table)

// Entry for `tag` (lowercase) in a Config being built; creates it (hold default 1, instant 0) when missing. nullptr when full.
int cfgEntry(Config& c, const char* tag, bool create = true) {
    for (int i = 0; i < c.nTags; ++i) if (!_stricmp(c.tags[i].tag, tag)) return i;
    if (!create || c.nTags >= MaxTagCfg) return -1;
    TagCfg& t = c.tags[c.nTags];
    snprintf(t.tag, sizeof t.tag, "%s", tag);
    t.preset = -1; t.instant = false; t.hold = true;
    c.presetId[c.nTags][0] = 0;
    return c.nTags++;
}

void reloadConfig(bool force = false) {
    if (!reloadDue(&g_cfgLast, &g_cfgChecked, force)) return;
    uint64_t st = fileStamp("levelup_override.ini");
    if (st == g_cfgStamp) return;
    g_cfgStamp = st;
    Config c;
    char legacy[MaxTagCfg][32]; int nLegacy = 0;
    bool hasInstant[MaxTagCfg] = {}, hasHold[MaxTagCfg] = {};
    if (FILE* f = fopen("levelup_override.ini", "r")) {
        char line[512];
        while (fgets(line, sizeof line, f)) {
            char* l = trim(line);
            if (!*l || *l == ';' || *l == '#') continue;
            char* eq = strchr(l, '=');
            if (!eq) continue;
            *eq = 0;
            char* k = trim(l); char* v = trim(eq + 1);
            lower(k);
            if (!strcmp(k, "mode")) {
                lower(v);
                c.mode = !strcmp(v, "off") ? Mode::Off : !strcmp(v, "rewrite") ? Mode::Rewrite : Mode::Log;
            } else if (!strcmp(k, "verbose")) {
                c.verbose = atoi(v) != 0;
            } else if (!strcmp(k, "apply")) {
                c.apply = atoi(v) != 0;
            } else if (!strcmp(k, "table")) {
                snprintf(c.table, sizeof c.table, "%s", v);
            } else if (!strcmp(k, "tags")) {
                lower(v);
                for (char* t = strtok(v, ","); t && nLegacy < MaxTagCfg; t = strtok(nullptr, ",")) {
                    t = trim(t);
                    if (*t) snprintf(legacy[nLegacy++], 32, "%s", t);
                }
            } else if (!strncmp(k, "preset.", 7) && k[7]) {
                int i = cfgEntry(c, k + 7);
                if (i >= 0) { lower(v); snprintf(c.presetId[i], sizeof c.presetId[i], "%s", v); }
            } else if (!strncmp(k, "instant.", 8) && k[8]) {
                int i = cfgEntry(c, k + 8);
                if (i >= 0) { c.tags[i].instant = atoi(v) != 0; hasInstant[i] = true; }
            } else if (!strncmp(k, "hold.", 5) && k[5]) {
                int i = cfgEntry(c, k + 5);
                if (i >= 0) { c.tags[i].hold = atoi(v) != 0; hasHold[i] = true; }
            }
        }
        fclose(f);
    }
    // Legacy allow-list: a tag without a preset key behaves as in 0.2.1 (preset <tag>__live, no instant, no hold).
    for (int j = 0; j < nLegacy; ++j) {
        int i = cfgEntry(c, legacy[j]);
        if (i < 0 || c.presetId[i][0]) continue;
        snprintf(c.presetId[i], sizeof c.presetId[i], "%s__live", c.tags[i].tag);
        if (!hasInstant[i]) c.tags[i].instant = false;
        if (!hasHold[i]) c.tags[i].hold = false;
    }
    g_cfg = c;
    resolvePresets();
    Buf b;
    for (int i = 0; i < c.nTags; ++i) b.add("%s%s:%s/i%d/h%d", i ? "," : "", c.tags[i].tag, c.presetId[i][0] ? c.presetId[i] : "-", c.tags[i].instant, c.tags[i].hold);
    logLine("CONFIG %s mode=%s apply=%d verbose=%d table=%s tags=%s", st ? "loaded" : "missing (defaults)",
            c.mode == Mode::Off ? "off" : c.mode == Mode::Rewrite ? "rewrite" : "log", c.apply, c.verbose, c.table, b.s);
}

// Per-tag configuration lookup (case-insensitive); nullptr = unconfigured -> every gate passes through.
// TODO(M3): consult the per-playthrough (save-bound) configuration FIRST and only fall back to the ini entries below.
const TagCfg* tagConfig(const char* tag) {
    if (!tag || !*tag) return nullptr;
    for (int i = 0; i < g_cfg.nTags; ++i) if (!_stricmp(g_cfg.tags[i].tag, tag)) return &g_cfg.tags[i];
    return nullptr;
}

// ---- runtime table v2 (levelup_paths.ini; format in gen_runtime_table.py docstring) ----------------------
constexpr int NumSkills = 8, MaxLevel = 50, MaxPresets = 128, MaxList = 16, MaxGranted = 24, MaxClass = 256;
constexpr size_t FileBufSize = 256 * 1024;
struct Rec {
    bool present; uint8_t cls, ability, clvl;   // clvl = creature level in `cls` after the record (0 = unknown, v1 file)
    int nFeats, nPowers, nSkills, nGranted;
    uint16_t feats[MaxList]; uint32_t powers[MaxList]; uint8_t skIdx[NumSkills], skRank[NumSkills];
    uint16_t granted[MaxGranted];
};
struct Preset {
    char id[48], tag[32], name[48], shortName[64];
    char role[16], style[16], alignment[16], convert[16], skills[16];
    int convertAt, holdClass;
    bool indexed;
    Rec lv[MaxLevel + 1];
};
Preset g_presets[MaxPresets];
int g_nPresets = 0;
uint8_t g_cs[MaxClass][NumSkills];
bool g_csHave[MaxClass];
bool g_tableOk = false;
uint64_t g_tableStamp = ~0ULL;
char g_tableErr[160] = "";
int g_tableWarn = 0;
char g_tableWarnIds[200] = "";
char g_fileBuf[FileBufSize];

// Parses "1,2,3" (may be empty) into out; false on a non-digit token or overflow.
template <typename T> bool parseIds(char* s, T* out, int cap, int* n, uint32_t maxv) {
    *n = 0;
    if (!*s) return true;
    for (char* p = s;;) {
        char* comma = strchr(p, ',');
        if (comma) *comma = 0;
        if (!*p || *n >= cap) return false;
        for (char* q = p; *q; ++q) if (*q < '0' || *q > '9') return false;
        unsigned long v = strtoul(p, nullptr, 10);
        if (v > maxv) return false;
        out[(*n)++] = static_cast<T>(v);
        if (!comma) return true;
        p = comma + 1;
    }
}
bool parseInt(char* s, int maxv, int* out) {
    uint32_t one[1]; int n;
    if (!parseIds(s, one, 1, &n, static_cast<uint32_t>(maxv)) || n != 1) return false;
    *out = static_cast<int>(one[0]);
    return true;
}

// L<n>=cls|ability|feats|powers|skill:ranks|granted|class_level   (6 fields = v1, class level unknown = 0)
bool parseRec(char* v, Rec* r) {
    char* f[7]; int nf = 0;
    f[nf++] = v;
    for (char* p = v; *p; ++p) if (*p == '|') { *p = 0; if (nf == 7) return false; f[nf++] = p + 1; }
    if (nf != 6 && nf != 7) return false;
    uint8_t one[1]; int n;
    if (!parseIds(f[0], one, 1, &n, 255) || n != 1) return false;
    r->cls = one[0];
    if (!parseIds(f[1], one, 1, &n, 6) || n != 1) return false;
    r->ability = one[0];
    if (!parseIds(f[2], r->feats, MaxList, &r->nFeats, 0xFFFF)) return false;
    if (!parseIds(f[3], r->powers, MaxList, &r->nPowers, 0xFFFFFF)) return false;
    if (!parseIds(f[5], r->granted, MaxGranted, &r->nGranted, 0xFFFF)) return false;
    r->clvl = 0;
    if (nf == 7) {
        if (!parseIds(f[6], one, 1, &n, 255) || n != 1) return false;
        r->clvl = one[0];
    }
    r->nSkills = 0;
    if (*f[4]) {
        for (char* p = f[4];;) {
            char* comma = strchr(p, ',');
            if (comma) *comma = 0;
            char* colon = strchr(p, ':');
            if (!colon || r->nSkills >= NumSkills) return false;
            *colon = 0;
            uint8_t a[1], b[1]; int na, nb;
            if (!parseIds(p, a, 1, &na, NumSkills - 1) || na != 1) return false;
            if (!parseIds(colon + 1, b, 1, &nb, 255) || nb != 1) return false;
            r->skIdx[r->nSkills] = a[0]; r->skRank[r->nSkills] = b[0]; ++r->nSkills;
            if (!comma) break;
            p = comma + 1;
        }
    }
    r->present = true;
    return true;
}

// Preset by id (lowercase compare), creating it when missing (nullptr when the table is full or the id is too long).
Preset* presetSlot(const char* id, bool create) {
    for (int i = 0; i < g_nPresets; ++i) if (!_stricmp(g_presets[i].id, id)) return &g_presets[i];
    if (!create || g_nPresets >= MaxPresets || strlen(id) >= sizeof g_presets[0].id || !*id) return nullptr;
    Preset* p = &g_presets[g_nPresets++];
    memset(p, 0, sizeof *p);
    snprintf(p->id, sizeof p->id, "%s", id);
    const char* us = strstr(id, "__");
    size_t tl = us ? static_cast<size_t>(us - id) : strlen(id);
    if (tl >= sizeof p->tag) tl = sizeof p->tag - 1;
    memcpy(p->tag, id, tl);
    p->tag[tl] = 0;
    return p;
}

bool parseTable(const char* path) {
    g_nPresets = 0;
    g_tableWarn = 0; g_tableWarnIds[0] = 0;
    memset(g_csHave, 0, sizeof g_csHave);
    FILE* f = fopen(path, "rb");
    if (!f) { snprintf(g_tableErr, sizeof g_tableErr, "cannot open %s", path); return false; }
    size_t len = fread(g_fileBuf, 1, sizeof g_fileBuf - 1, f);
    bool full = feof(f) != 0;
    fclose(f);
    if (!full) { snprintf(g_tableErr, sizeof g_tableErr, "%s larger than %u bytes", path, (unsigned)sizeof g_fileBuf - 1); return false; }
    g_fileBuf[len] = 0;
    enum { None, ClassSkills, PresetIndex, PresetSec } sec = None;
    Preset* cur = nullptr;
    int lineNo = 0;
    for (char* line = g_fileBuf; line;) {
        char* nl = strchr(line, '\n');
        if (nl) *nl = 0;
        ++lineNo;
        char* l = trim(line);
        line = nl ? nl + 1 : nullptr;
        if (!*l || *l == ';') continue;
        if (*l == '[') {
            char* e = strchr(l, ']');
            if (!e) goto bad;
            *e = 0; ++l; lower(l);
            if (!strcmp(l, "classskills")) { sec = ClassSkills; continue; }
            if (!strcmp(l, "presets")) { sec = PresetIndex; continue; }
            cur = presetSlot(l, true);
            if (!cur) goto bad;
            sec = PresetSec;
            continue;
        }
        char* eq = strchr(l, '=');
        if (!eq) goto bad;
        *eq = 0;
        char* k = trim(l); char* v = trim(eq + 1);
        lower(k);
        if (sec == ClassSkills) {
            if (k[0] != 'c' || k[1] != 's') goto bad;
            uint8_t c[1]; int n;
            if (!parseIds(k + 2, c, 1, &n, MaxClass - 1) || n != 1 || strlen(v) != NumSkills) goto bad;
            for (int i = 0; i < NumSkills; ++i) {
                if (v[i] != '0' && v[i] != '1') goto bad;
                g_cs[c[0]][i] = v[i] == '1';
            }
            g_csHave[c[0]] = true;
        } else if (sec == PresetIndex) {
            // <id>=role|style|alignment|convert|skills|convert_at|hold_class|short
            char* fl[8]; int nf = 0;
            fl[nf++] = v;
            for (char* p = v; *p; ++p) if (*p == '|') { *p = 0; if (nf == 8) goto bad; fl[nf++] = p + 1; }
            if (nf != 8) goto bad;
            Preset* p = presetSlot(k, true);
            if (!p) goto bad;
            int ca = 0, hc = 0;
            if (!parseInt(fl[5], MaxLevel, &ca) || !parseInt(fl[6], 255, &hc)) goto bad;
            snprintf(p->role, sizeof p->role, "%s", fl[0]);
            snprintf(p->style, sizeof p->style, "%s", fl[1]);
            snprintf(p->alignment, sizeof p->alignment, "%s", fl[2]);
            snprintf(p->convert, sizeof p->convert, "%s", fl[3]);
            snprintf(p->skills, sizeof p->skills, "%s", fl[4]);
            snprintf(p->shortName, sizeof p->shortName, "%s", fl[7]);
            p->convertAt = ca; p->holdClass = hc; p->indexed = true;
        } else if (sec == PresetSec) {
            if (!strcmp(k, "name")) { snprintf(cur->name, sizeof cur->name, "%s", v); continue; }
            if (k[0] != 'l') goto bad;
            uint8_t lv[1]; int n;
            if (!parseIds(k + 1, lv, 1, &n, MaxLevel) || n != 1) goto bad;
            if (!parseRec(v, &cur->lv[lv[0]])) goto bad;
        } else {
            goto bad;
        }
    }
    for (int i = 0; i < g_nPresets; ++i) {   // a preset section without an index row: hold_class 0 + a warning
        if (g_presets[i].indexed) continue;
        ++g_tableWarn;
        size_t n = strlen(g_tableWarnIds);
        snprintf(g_tableWarnIds + n, sizeof g_tableWarnIds - n, " %s", g_presets[i].id);
    }
    return true;
bad:
    snprintf(g_tableErr, sizeof g_tableErr, "%s line %d malformed", path, lineNo);
    g_nPresets = 0;
    return false;
}

void reloadTable(bool force = false) {
    if (!reloadDue(&g_tableLast, &g_tableChecked, force)) return;
    uint64_t st = fileStamp(g_cfg.table);
    if (st == g_tableStamp) return;
    g_tableStamp = st;
    g_tableOk = parseTable(g_cfg.table);
    resolvePresets();
    if (g_tableOk) {
        Buf b;
        int total = 0;
        for (int t = 0; t < g_nPresets; ++t) {
            int n = 0;
            for (int i = 0; i <= MaxLevel; ++i) n += g_presets[t].lv[i].present;
            total += n;
        }
        for (int i = 0; i < g_cfg.nTags; ++i) {
            const TagCfg& tc = g_cfg.tags[i];
            b.add(" %s=%s", tc.tag, tc.preset >= 0 ? g_presets[tc.preset].id : "UNRESOLVED");
        }
        logLine("TABLE loaded %s: %d presets, %d records;%s", g_cfg.table, g_nPresets, total, b.s);
        if (g_tableWarn) logLine("TABLE warning: %d preset section(s) without an index row (hold_class 0):%s", g_tableWarn, g_tableWarnIds);
    } else {
        logLine("TABLE ERROR %s -> rewrite disabled", g_tableErr);
    }
}

int findPresetIdx(const char* id) {
    if (!g_tableOk || !id || !*id) return -1;
    for (int i = 0; i < g_nPresets; ++i) if (!_stricmp(g_presets[i].id, id)) return i;
    return -1;
}
const Preset* findPreset(const char* id) {
    int i = findPresetIdx(id);
    return i < 0 ? nullptr : &g_presets[i];
}
void resolvePresets() {
    for (int i = 0; i < g_cfg.nTags; ++i) g_cfg.tags[i].preset = findPresetIdx(g_cfg.presetId[i]);
}
[[maybe_unused]] const Rec* lookupRecord(const char* id, int keyLevel) {
    const Preset* p = findPreset(id);
    if (!p || keyLevel < 0 || keyLevel > MaxLevel || !p->lv[keyLevel].present) return nullptr;
    return &p->lv[keyLevel];
}

// ---- levelNow: hold rule v2, keyed by CLASS level (twin: simulate_rewrite.py level_now) ------------------
enum class Decision { Vanilla, Path, Rebase, Hold };
const char* decisionName(Decision d) { return d == Decision::Path ? "PATH" : d == Decision::Rebase ? "REBASE" : d == Decision::Hold ? "HOLD" : "VANILLA"; }

// clsId/clsLvl: the creature's class entries in engine order (newest = last). key = total character level + 1.
// PATH/REBASE: the record whose (class, class level) == (newest class, its level + 1); PATH when its char level == key.
// HOLD: no such record, hold && the preset has a hold class the creature lacks, and the preset's records for the newest class are used up.
Decision levelNow(const uint8_t* clsId, const uint8_t* clsLvl, int nClass, const Preset* p, int key, bool hold, const Rec** outRec, int* outCharLevel) {
    if (outRec) *outRec = nullptr;
    if (outCharLevel) *outCharLevel = -1;
    if (!p || nClass <= 0) return Decision::Vanilla;
    const int cls = clsId[nClass - 1], lvl = clsLvl[nClass - 1];
    int top = -1;
    for (int cl = 0; cl <= MaxLevel; ++cl) {
        const Rec& r = p->lv[cl];
        if (!r.present || r.clvl == 0) continue;   // clvl 0 = unknown: never matches
        if (r.cls == cls && r.clvl == lvl + 1) {
            if (outRec) *outRec = &r;
            if (outCharLevel) *outCharLevel = cl;
            return cl == key ? Decision::Path : Decision::Rebase;
        }
        if (r.cls == cls && r.clvl > top) top = r.clvl;
    }
    if (hold && p->holdClass && top >= 0 && lvl >= top) {
        bool has = false;
        for (int i = 0; i < nClass; ++i) if (clsId[i] == p->holdClass) has = true;
        if (!has) return Decision::Hold;
    }
    return Decision::Vanilla;
}

// ---- dry-run algorithm (twin: simulate_rewrite.py compute_rewrite) ------------------------------------------
constexpr int MaxPend = 64;
struct Pend {
    int cls, ability, unspent;
    int nFeats, nSpells;
    uint16_t feats[MaxPend]; uint32_t spells[MaxPend];
    int deltas[NumSkills];
};
// nKeptFeats/nKeptSpells: out.feats[0..nKeptFeats) / out.spells[0..nKeptSpells) are entries taken from `in` (in order); the rest are path ids.
struct Result { const char* status; Pend p; int nKeptFeats = 0, nKeptSpells = 0; };

// csExtra bit i = skill i is a class skill through a Class Skill feat (183-189) the creature already has.
int skillCost(const int* d, int cls, uint8_t csExtra) {
    int c = 0;
    for (int i = 0; i < NumSkills; ++i)
        c += d[i] * ((cls >= 0 && cls < MaxClass && g_csHave[cls] && !g_cs[cls][i] && !((csExtra >> i) & 1)) ? 2 : 1);
    return c;
}
// Class Skill feat id -> skill index (-1 = not one).
int classSkillFeatSkill(uint32_t feat) {
    static const int8_t map[7] = {3, 0, 1, 5, 6, 2, 7};   // 183 Awareness, 184 Computer Use, 185 Demolitions, 186 Repair, 187 Security, 188 Stealth, 189 Treat Injury
    return feat >= 183 && feat <= 189 ? map[feat - 183] : -1;
}
template <typename T> bool has(const T* a, int n, uint32_t v) { for (int i = 0; i < n; ++i) if (a[i] == v) return true; return false; }

Result computeRewrite(const Rec* r, const Pend& in, uint8_t csExtra = 0) {
    Result res{"rewrite", in};
    if (!r) { res.status = "no-record"; return res; }
    if (r->cls != in.cls) { res.status = "class-mismatch"; return res; }
    Pend& o = res.p;
    o.nFeats = 0;
    for (int i = 0; i < in.nFeats; ++i) if (has(r->granted, r->nGranted, in.feats[i])) o.feats[o.nFeats++] = in.feats[i];
    res.nKeptFeats = o.nFeats;
    for (int i = 0; i < r->nFeats; ++i) if (!has(o.feats, o.nFeats, r->feats[i]) && o.nFeats < MaxPend) o.feats[o.nFeats++] = r->feats[i];
    o.nSpells = 0;
    for (int i = 0; i < in.nSpells; ++i) if (isEngineGrantPower(in.spells[i])) o.spells[o.nSpells++] = in.spells[i];
    res.nKeptSpells = o.nSpells;
    for (int i = 0; i < r->nPowers; ++i) if (!has(o.spells, o.nSpells, r->powers[i]) && o.nSpells < MaxPend) o.spells[o.nSpells++] = r->powers[i];
    for (int i = 0; i < NumSkills; ++i) o.deltas[i] = 0;
    for (int i = 0; i < r->nSkills; ++i) o.deltas[r->skIdx[i]] = r->skRank[i];
    o.unspent = in.unspent + skillCost(in.deltas, in.cls, csExtra) - skillCost(o.deltas, in.cls, csExtra);
    if (o.unspent < 0) { res.status = "negative-unspent"; res.p = in; return res; }
    o.ability = r->ability != 6 ? r->ability : in.ability;
    bool same = o.nFeats == in.nFeats && o.nSpells == in.nSpells && o.unspent == in.unspent && o.ability == in.ability &&
                !memcmp(o.feats, in.feats, sizeof(uint16_t) * in.nFeats) && !memcmp(o.spells, in.spells, sizeof(uint32_t) * in.nSpells) &&
                !memcmp(o.deltas, in.deltas, sizeof o.deltas);
    if (same) res.status = "already";
    return res;
}

void formatDry(Buf& b, const char* tag, int key, const Result& r) {
    b.add("DRY tag=%s key=%d status=%s feats=[", tag, key, r.status);
    for (int i = 0; i < r.p.nFeats; ++i) b.add("%s%u", i ? "," : "", r.p.feats[i]);
    b.add("] spells=[");
    for (int i = 0; i < r.p.nSpells; ++i) b.add("%s%u", i ? "," : "", r.p.spells[i]);
    b.add("] deltas=[");
    for (int i = 0; i < NumSkills; ++i) b.add("%s%d", i ? "," : "", r.p.deltas[i]);
    b.add("] unspent=%d ability=%d", r.p.unspent, r.p.ability);
}

// ---- dump helpers (every read SafeRead-guarded) -------------------------------------------------------------
enum Site : unsigned { S_Tag = 1, S_Class, S_Stats, S_Ranks, S_FeatList, S_Pend, S_PendArr, S_Rules, S_Frame };

// Tag of a creature object (CExoString {char*, len} at +0x18); false = unreadable or empty (the PC has an empty tag).
bool readCreatureTag(uintptr_t cr, char* out, int cap) {
    out[0] = 0;
    uint32_t str = 0, len = 0;   // engine pointers are 32-bit
    if (!readAt(S_Tag, cr, Cr_Tag, &str) || !readAt(S_Tag, cr, Cr_Tag + 4, &len)) return false;
    if (!str || len == 0 || len >= static_cast<uint32_t>(cap) || !probeRead(S_Tag, reinterpret_cast<const void*>(static_cast<uintptr_t>(str)), len)) return false;
    memcpy(out, reinterpret_cast<const void*>(static_cast<uintptr_t>(str)), len);
    out[len] = 0;
    return true;
}
// Tag via stats+0x24 (creature pointer).
bool readTag(uintptr_t stats, char* out, int cap) {
    uint32_t cr = 0;
    out[0] = 0;
    return readAt(S_Tag, stats, St_Creature, &cr) && readCreatureTag(cr, out, cap);
}

// Reads an engine {ptr,count,cap} array header + up to MaxPend elements of size esz into out (as uint32).
bool readArr(uintptr_t base, int off, int esz, uint32_t* out, int* n, uint32_t* count, uint32_t* cap) {
    uint32_t p = 0;   // engine pointer (32-bit)
    *n = 0;
    if (!readAt(S_PendArr, base, off, &p) || !readAt(S_PendArr, base, off + 4, count) || !readAt(S_PendArr, base, off + 8, cap)) return false;
    int take = *count > static_cast<uint32_t>(MaxPend) ? MaxPend : static_cast<int>(*count);
    if (take == 0) return true;
    const uintptr_t a = p;
    if (!a || !probeRead(S_PendArr, reinterpret_cast<const void*>(a), static_cast<size_t>(take) * esz)) return false;
    for (int i = 0; i < take; ++i)
        out[i] = esz == 2 ? reinterpret_cast<const uint16_t*>(a)[i] : reinterpret_cast<const uint32_t*>(a)[i];
    *n = take;
    return true;
}

void listAdd(Buf& b, const uint32_t* v, int n, bool hex = false) {
    for (int i = 0; i < n; ++i) b.add(hex ? "%s0x%x" : "%s%u", i ? "," : "", v[i]);
}

// ---- pending struct read (entry dump, and the AFTER re-read once applyRewrite has run) ----------------------
struct PendDump {
    bool ok = false;                     // the 0x30 bytes were readable
    uint8_t raw[Pd_Size] = {};
    Pend pd{};
    bool featsOk = false, spellsOk = false, remOk = false, deltasOk = false;
    uint32_t fCnt = 0, fCap = 0, sCnt = 0, sCap = 0, rCnt = 0, rCap = 0;
    uint32_t rem[MaxPend] = {}; int nRem = 0;
    uint8_t deltas[32] = {};
};

bool readPend(uintptr_t pending, int nSkills, PendDump* d) {
    *d = PendDump{};
    d->ok = pending && probeRead(S_Pend, reinterpret_cast<const void*>(pending), Pd_Size);
    if (!d->ok) return false;
    memcpy(d->raw, reinterpret_cast<const void*>(pending), Pd_Size);
    Pend& pd = d->pd;
    pd.cls = d->raw[Pd_Class];
    pd.ability = d->raw[Pd_Ability];
    pd.unspent = *reinterpret_cast<const uint16_t*>(d->raw + Pd_Unspent);
    uint32_t tmp[MaxPend]; int n = 0;
    d->featsOk = readArr(pending, Pd_Feats, 2, tmp, &n, &d->fCnt, &d->fCap);
    pd.nFeats = n;
    for (int i = 0; i < n; ++i) pd.feats[i] = static_cast<uint16_t>(tmp[i]);
    d->spellsOk = readArr(pending, Pd_SpellsAdd, 4, pd.spells, &n, &d->sCnt, &d->sCap);
    pd.nSpells = n;
    d->remOk = readArr(pending, Pd_SpellsRem, 4, d->rem, &d->nRem, &d->rCnt, &d->rCap);
    const uintptr_t deltasP = *reinterpret_cast<const uint32_t*>(d->raw + Pd_Deltas);
    d->deltasOk = nSkills && deltasP && probeRead(S_PendArr, reinterpret_cast<const void*>(deltasP), nSkills);
    if (d->deltasOk) memcpy(d->deltas, reinterpret_cast<const void*>(deltasP), nSkills);
    for (int i = 0; i < NumSkills; ++i) pd.deltas[i] = d->deltas[i];
    return true;
}

void logPend(const char* pfx, const PendDump& d, int nSkills) {
    Buf b;
    b.add("  %s: class=%u ability=%u hp=%u force=%u unspent28=%u skills(n=%u)%s=[", pfx, d.raw[Pd_Class], d.raw[Pd_Ability], d.raw[Pd_HP],
          d.raw[Pd_Force], d.pd.unspent, nSkills, d.deltasOk ? "" : "UNREADABLE");
    for (int i = 0; i < nSkills; ++i) b.add("%s%u", i ? "," : "", d.deltas[i]);
    b.add("]");
    logf("%s", b.s);
    Buf f;
    f.add("  %s.feats%s count=%u cap=%u [", pfx, d.featsOk ? "" : " UNREADABLE", d.fCnt, d.fCap);
    for (int i = 0; i < d.pd.nFeats; ++i) f.add("%s%u", i ? "," : "", d.pd.feats[i]);
    f.add("]");
    logf("%s", f.s);
    Buf s;
    s.add("  %s.spellsAdd%s count=%u cap=%u [", pfx, d.spellsOk ? "" : " UNREADABLE", d.sCnt, d.sCap);
    listAdd(s, d.pd.spells, d.pd.nSpells, true);
    s.add("] spellsRem%s count=%u cap=%u [", d.remOk ? "" : " UNREADABLE", d.rCnt, d.rCap);
    listAdd(s, d.rem, d.nRem, true);
    s.add("]");
    logf("%s", s.s);
    Buf h;
    h.add("  %s.raw", pfx);
    for (int i = 0; i < Pd_Size; ++i) h.add("%s%02x", (i % 4) ? "" : " ", d.raw[i]);
    logf("%s", h.s);
}

bool samePend(const Pend& a, const Pend& b) {
    return a.cls == b.cls && a.ability == b.ability && a.unspent == b.unspent && a.nFeats == b.nFeats && a.nSpells == b.nSpells &&
           !memcmp(a.feats, b.feats, sizeof(uint16_t) * a.nFeats) && !memcmp(a.spells, b.spells, sizeof(uint32_t) * a.nSpells) &&
           !memcmp(a.deltas, b.deltas, sizeof a.deltas);
}

// ---- apply (doc 08 "Phase 1b results" O5; engine helpers verified in phase1b_disasm.txt / phase1b_containers.txt) ----
// All three are thiscall. AddFeat: ECX = pending (it adds +0x18 itself), dedups against the pending feat list, then pushes; ret 4.
// SetSkillDelta: ECX = pending, (ushort idx, byte value), ignores idx >= rules+0x123; ret 8. PushU32: ECX = array header
// {ptr, int count, int cap} (pending+0x00 = spells-add, as AutoLevelup 0x6BFF7E does), grows 16 then x2 via 0x84A680; ret 4.
typedef void (__thiscall* AddFeat_t)(void* pending, uint16_t feat);
typedef void (__thiscall* SetSkillDelta_t)(void* pending, uint16_t idx, uint8_t value);
typedef void (__thiscall* PushU32_t)(void* arr, uint32_t value);
// Gate functions (all thiscall; the originals the hooked call sites used to call): canLevelUp(stats) plain RET; optAccessor(ecx) (__fastcall,
// ECX only); charChange 0x740FC0 (GetCharacterChangeInProgress) plain RET; getCreature 0x77D800 (-> creature*); partyGet 0x7E5DA0(party, idx) RET 4;
// tableGet 0x73FB90 (-> party). appGlobal = address of the global holding the app object (+4 = table-get ECX).
struct Engine {
    uintptr_t addFeat, setSkillDelta, pushU32;
    bool checkCode;   // compare the functions' first bytes before calling (off in the host test, which uses fakes)
    uintptr_t canLevelUp = 0x006B9790, optAccessor = 0x0072FB00, charChange = 0x00740FC0, getCreature = 0x0077D800,
              partyGet = 0x007E5DA0, tableGet = 0x0073FB90, appGlobal = 0x00A1B4A4;
};
Engine g_eng = {0x006F5B40, 0x006F5B00, 0x0083EA60, true};
const uint8_t kAddFeatCode[] = {0x55, 0x8B, 0xEC, 0x51, 0x89, 0x4D, 0xFC};
const uint8_t kSetSkillDeltaCode[] = {0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x08, 0x89, 0x4D, 0xF8};
const uint8_t kPushU32Code[] = {0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x08, 0x89, 0x4D, 0xFC};

const uint8_t kCanLevelUpCode[] = {0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x20, 0x56, 0x89, 0x4D};
const uint8_t kOptAccessorCode[] = {0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x08, 0x89, 0x4D, 0xF8};
const uint8_t kCharChangeCode[] = {0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x08, 0x89, 0x4D, 0xF8};
const uint8_t kGetCreatureCode[] = {0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x08, 0x89, 0x4D, 0xFC};
const uint8_t kPartyGetCode[] = {0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x0C, 0x89, 0x4D, 0xF4};
const uint8_t kTableGetCode[] = {0x55, 0x8B, 0xEC, 0x83, 0xEC, 0x08, 0x89, 0x4D, 0xF8};

bool writableProtect(DWORD p) {
    if (p & (PAGE_GUARD | PAGE_NOACCESS)) return false;
    return (p & (PAGE_READWRITE | PAGE_WRITECOPY | PAGE_EXECUTE_READWRITE | PAGE_EXECUTE_WRITECOPY)) != 0;
}
// [p, p+len) fully inside committed writable memory (walks consecutive regions; never faults).
bool probeWritable(const void* p, size_t len) {
    uintptr_t a = reinterpret_cast<uintptr_t>(p), end = a + len;
    if (a < 0x10000 || end < a) return false;
    while (a < end) {
        MEMORY_BASIC_INFORMATION mbi;
        if (VirtualQuery(reinterpret_cast<LPCVOID>(a), &mbi, sizeof mbi) != sizeof mbi) return false;
        if (mbi.State != MEM_COMMIT || !writableProtect(mbi.Protect)) return false;
        a = reinterpret_cast<uintptr_t>(mbi.BaseAddress) + mbi.RegionSize;
    }
    return true;
}
bool codeMatches(uintptr_t fn, const uint8_t* code, size_t n) {
    return probeRead(S_Pend, reinterpret_cast<const void*>(fn), n) && !memcmp(reinterpret_cast<const void*>(fn), code, n);
}

// Writes res.p into the pending struct `in` was read from. Every precondition is checked before the first write; on failure logs
// "APPLY ABORTED <why>" and returns false with the struct untouched. Never allocates: removals compact in place and lower the
// count, additions go through the engine's own push helpers (its allocator owns the arrays).
bool applyRewrite(uintptr_t pending, const Pend& in, const Result& res, int nSkills) {
    const Pend& out = res.p;
    const char* why = nullptr;
    uint32_t fPtr = 0, fCnt = 0, sPtr = 0, sCnt = 0, dPtr = 0;
    if (nSkills != NumSkills) why = "skill count";
    else if (!probeWritable(reinterpret_cast<const void*>(pending), Pd_Size)) why = "pending not writable";
    else {
        fPtr = *reinterpret_cast<const uint32_t*>(pending + Pd_Feats);
        fCnt = *reinterpret_cast<const uint32_t*>(pending + Pd_Feats + 4);
        sPtr = *reinterpret_cast<const uint32_t*>(pending + Pd_SpellsAdd);
        sCnt = *reinterpret_cast<const uint32_t*>(pending + Pd_SpellsAdd + 4);
        dPtr = *reinterpret_cast<const uint32_t*>(pending + Pd_Deltas);
        if (fCnt != static_cast<uint32_t>(in.nFeats) || sCnt != static_cast<uint32_t>(in.nSpells)) why = "counts changed since read";
        else if (res.nKeptFeats > in.nFeats || res.nKeptSpells > in.nSpells || res.nKeptFeats > out.nFeats || res.nKeptSpells > out.nSpells)
            why = "kept prefix out of range";
        else if (in.nFeats && !probeWritable(reinterpret_cast<const void*>(static_cast<uintptr_t>(fPtr)), in.nFeats * 2u)) why = "feats not writable";
        else if (in.nSpells && !probeWritable(reinterpret_cast<const void*>(static_cast<uintptr_t>(sPtr)), in.nSpells * 4u)) why = "spells not writable";
        else if (!probeWritable(reinterpret_cast<const void*>(static_cast<uintptr_t>(dPtr)), NumSkills)) why = "deltas not writable";
        else if (!g_eng.addFeat || !g_eng.setSkillDelta || !g_eng.pushU32) why = "engine helper missing";
        else if (g_eng.checkCode && (!codeMatches(g_eng.addFeat, kAddFeatCode, sizeof kAddFeatCode) ||
                                     !codeMatches(g_eng.setSkillDelta, kSetSkillDeltaCode, sizeof kSetSkillDeltaCode) ||
                                     !codeMatches(g_eng.pushU32, kPushU32Code, sizeof kPushU32Code)))
            why = "engine helper bytes differ";
    }
    if (why) { logf("  APPLY ABORTED %s - vanilla (no write)", why); return false; }

    void* pd = reinterpret_cast<void*>(pending);
    // (1) feats: kept prefix in place, then path feats via AddFeat (ECX = pending)
    uint16_t* fa = reinterpret_cast<uint16_t*>(static_cast<uintptr_t>(fPtr));
    for (int i = 0; i < res.nKeptFeats; ++i) fa[i] = out.feats[i];
    *reinterpret_cast<uint32_t*>(pending + Pd_Feats + 4) = static_cast<uint32_t>(res.nKeptFeats);
    for (int i = res.nKeptFeats; i < out.nFeats; ++i) reinterpret_cast<AddFeat_t>(g_eng.addFeat)(pd, out.feats[i]);
    // (2) spells-add: kept prefix in place, then path powers via PushU32 (ECX = pending+0x00 array header); spells-remove untouched
    uint32_t* sa = reinterpret_cast<uint32_t*>(static_cast<uintptr_t>(sPtr));
    for (int i = 0; i < res.nKeptSpells; ++i) sa[i] = out.spells[i];
    *reinterpret_cast<uint32_t*>(pending + Pd_SpellsAdd + 4) = static_cast<uint32_t>(res.nKeptSpells);
    for (int i = res.nKeptSpells; i < out.nSpells; ++i)
        reinterpret_cast<PushU32_t>(g_eng.pushU32)(reinterpret_cast<void*>(pending + Pd_SpellsAdd), out.spells[i]);
    // (3) skill deltas, (4) unspent, (5) ability
    for (int i = 0; i < NumSkills; ++i)
        reinterpret_cast<SetSkillDelta_t>(g_eng.setSkillDelta)(pd, static_cast<uint16_t>(i), static_cast<uint8_t>(out.deltas[i]));
    *reinterpret_cast<uint16_t*>(pending + Pd_Unspent) = static_cast<uint16_t>(out.unspent);
    *reinterpret_cast<uint8_t*>(pending + Pd_Ability) = static_cast<uint8_t>(out.ability);
    return true;
}

volatile LONG g_calls = 0;
bool g_headerDone = false;

void rotateIfLarge() {
    WIN32_FILE_ATTRIBUTE_DATA d;
    if (GetFileAttributesExA(LogName, GetFileExInfoStandard, &d) && (d.nFileSizeHigh || d.nFileSizeLow > static_cast<DWORD>(RotateBytes))) {
        DeleteFileA("levelup_override_log.old.txt");
        MoveFileA(LogName, "levelup_override_log.old.txt");
    }
}

// True when CSWSCreatureStats::AutoLevelup (0x6BEDF0) is on the call chain: the engine chose the picks (Auto button, Auto Level Up
// NPCs, XP-award auto levels). Only those level-ups are rewritten; a player's manual GUI picks (and SetExperience replays of them) are kept.
bool viaAutoLevelup(uintptr_t ret, const uintptr_t* frames, int nFrames) {
    const Fn* d = findFn(ret);
    if (d && d->lo == 0x006BEDF0) return true;
    for (int i = 0; i < nFrames; ++i) {
        const Fn* f = findFn(frames[i]);
        if (f && f->lo == 0x006BEDF0) return true;
    }
    return false;
}

// Returns the flow name from the direct return address and the EBP chain (nearest frame that names a flow wins).
const char* classify(uintptr_t ret, const uintptr_t* frames, int nFrames) {
    const Fn* d = findFn(ret);
    if (d && d->flow) return d->flow;
    for (int i = 0; i < nFrames; ++i) {
        const Fn* f = findFn(frames[i]);
        if (f && f->flow) return f->flow;
    }
    for (int i = 0; i < nFrames; ++i) {
        const Fn* f = findFn(frames[i]);
        if (f && f->lo == 0x006BEDF0) return "auto-other";
    }
    return "unknown";
}

// Once per process, from whichever hook runs first (the gates run every frame, before the first LevelUp call).
void ensureHeader() {
    if (g_headerDone) return;
    g_headerDone = true;
    rotateIfLarge();
    logLine("== LevelUpOverride %s loaded; first hook call (build apply=%d) ==", Version, ApplyEnabled);
}

// The creature's class entries (engine order, newest last) and total level; false when unreadable or not 1..4 classes.
bool readClasses(uintptr_t stats, uint8_t* ids, uint8_t* lvls, int* n, int* total) {
    uint8_t cnt = 0;
    *n = 0; *total = 0;
    if (!readAt(S_Class, stats, St_ClassCount, &cnt) || cnt < 1 || cnt > 4) return false;
    for (int i = 0; i < cnt; ++i) {
        if (!readAt(S_Class, stats, St_ClassId + i * St_ClassStride, &ids[i]) || !readAt(S_Class, stats, St_ClassLevel + i * St_ClassStride, &lvls[i])) return false;
        *total += lvls[i];
    }
    *n = cnt;
    return true;
}

// Bit i set = the creature already has the Class Skill feat (183-189) of skill i (both creature feat lists, as HasFeat 0x6B83F0 checks).
uint8_t classSkillMask(uintptr_t stats) {
    uint8_t mask = 0;
    const int lists[2] = {St_FeatList, St_FeatList2};
    for (int L = 0; L < 2; ++L) {
        uint32_t fl = 0, fc = 0;
        if (!readAt(S_FeatList, stats, lists[L], &fl) || !readAt(S_FeatList, stats, lists[L] + 4, &fc) || !fl) continue;
        uint32_t take = fc > 200 ? 200 : fc;
        const uintptr_t a = fl;
        if (!take || !probeRead(S_FeatList, reinterpret_cast<const void*>(a), take * 2)) continue;
        for (uint32_t i = 0; i < take; ++i) {
            int sk = classSkillFeatSkill(reinterpret_cast<const uint16_t*>(a)[i]);
            if (sk >= 0) mask |= static_cast<uint8_t>(1u << sk);
        }
    }
    return mask;
}

void onLevelUp(uintptr_t stats, uintptr_t ret, uintptr_t pending, int addToList, uintptr_t ebp) {
    LONG call = InterlockedIncrement(&g_calls);
    ensureHeader();
    reloadConfig(true);
    if (g_cfg.mode == Mode::Off) return;
    reloadTable(true);
    if (!logOpen()) return;
    const bool v = g_cfg.verbose;

    // -- caller chain: EBP at hook time = LevelUp's caller frame; [ebp+4] = caller's return address
    uintptr_t frames[4]; int nFrames = 0;
    for (uintptr_t e = ebp; nFrames < 4;) {
        uintptr_t next = 0, r = 0;
        if (!readAt(S_Frame, e, 4, &r) || !readAt(S_Frame, e, 0, &next)) break;
        frames[nFrames++] = r;
        if (next <= e || next - e > 0x100000) break;
        e = next;
    }
    const char* flow = classify(ret, frames, nFrames);
    const bool viaAuto = viaAutoLevelup(ret, frames, nFrames);
    Buf chain;
    const Fn* rf = findFn(ret);
    chain.add("ret=%08x(%s)", (unsigned)ret, rf ? rf->name : "?");
    for (int i = 0; i < nFrames; ++i) {
        const Fn* f = findFn(frames[i]);
        chain.add(" <- %08x(%s)", (unsigned)frames[i], f ? f->name : "?");
    }

    // -- creature
    char tag[32];
    bool tagOk = readTag(stats, tag, sizeof tag);
    if (!tagOk) strcpy(tag, "?");
    uint8_t nClass = 0;
    int total = 0;
    uint8_t cIds[4] = {}, cLvls[4] = {};
    int nGot = 0;
    Buf cls;
    if (readAt(S_Class, stats, St_ClassCount, &nClass)) {
        if (nClass > 4) { cls.add("count=%u?", nClass); total = -1; nClass = 0; }
        for (int i = 0; i < nClass; ++i) {
            uint8_t id = 0, lv = 0, neg = 0;
            if (!readAt(S_Class, stats, St_ClassId + i * St_ClassStride, &id) || !readAt(S_Class, stats, St_ClassLevel + i * St_ClassStride, &lv) ||
                !readAt(S_Class, stats, St_ClassNeg + i * St_ClassStride, &neg)) { cls.add(" ?"); total = -1; break; }
            cIds[i] = id; cLvls[i] = lv; nGot = i + 1;
            cls.add("%s%u:%u%s", i ? "," : "", id, lv, neg ? "(neg)" : "");
            if (neg) cls.add("%u", neg);
            total += lv;
        }
    } else {
        total = -1;
    }
    uint32_t xp = 0; uint16_t stUnspent = 0;
    readAt(S_Stats, stats, St_XP, &xp);
    readAt(S_Stats, stats, St_Unspent, &stUnspent);

    uintptr_t rules = 0; uint8_t nSkills = 0;
    if (readAt(S_Rules, RulesGlobal, 0, &rules)) readAt(S_Rules, rules, Rules_SkillCount, &nSkills);
    if (nSkills > 32) nSkills = 32;

    // -- pending
    PendDump dp;
    readPend(pending, nSkills, &dp);
    int key = total >= 0 ? total + 1 : -1;

    logf("[%lu] #%ld tid=%lu flow=%s %s stats=%08x pending=%08x addToList=%d tag=%s classes=%s total=%d key=%d xp=%u unspent170=%u",
         GetTickCount(), call, GetCurrentThreadId(), flow, chain.s, (unsigned)stats, (unsigned)pending, addToList, tag, cls.s, total, key,
         xp, stUnspent);

    if (!dp.ok) { logf("  pending unreadable -> vanilla"); logClose(); return; }
    const Pend& pd = dp.pd;

    if (v) {
        logPend("pend", dp, nSkills);

        // creature skill ranks and feat list (before LevelUp applies anything)
        Buf r;
        uintptr_t ranksP = 0;
        r.add("  stats.ranks=[");
        if (readAt(S_Ranks, stats, St_SkillRanks, &ranksP) && nSkills && probeRead(S_Ranks, reinterpret_cast<const void*>(ranksP), nSkills))
            for (int i = 0; i < nSkills; ++i) r.add("%s%u", i ? "," : "", reinterpret_cast<const uint8_t*>(ranksP)[i]);
        else
            r.add("UNREADABLE");
        r.add("]");
        logf("%s", r.s);
        // feat lists: +0x00 full list, +0x18 second list (both {ushort*, count}; HasFeat 0x6B83F0 checks both)
        const int lists[2] = {St_FeatList, St_FeatList2};
        for (int L = 0; L < 2; ++L) {
            Buf fb;
            uintptr_t fl = 0; uint32_t fc = 0;
            fb.add("  stats.feats%s", L ? "2" : "");
            if (readAt(S_FeatList, stats, lists[L], &fl) && readAt(S_FeatList, stats, lists[L] + 4, &fc)) {
                uint32_t take = fc > 200 ? 200 : fc;
                fb.add(" count=%u [", fc);
                if (take && fl && probeRead(S_FeatList, reinterpret_cast<const void*>(fl), take * 2))
                    for (uint32_t i = 0; i < take; ++i) fb.add("%s%u", i ? "," : "", reinterpret_cast<const uint16_t*>(fl)[i]);
                fb.add("]");
            } else {
                fb.add(" UNREADABLE");
            }
            logf("%s", fb.s);
        }
    }

    // -- decision + dry run for tags configured with a preset; rewrite when mode=rewrite (auto level-ups only)
    const TagCfg* cfg = tagOk ? tagConfig(tag) : nullptr;
    const Preset* preset = cfg && cfg->preset >= 0 && g_tableOk ? &g_presets[cfg->preset] : nullptr;
    const bool rewriteTag = g_cfg.mode == Mode::Rewrite && preset;
    if (preset) {
        const Rec* rec = nullptr; int recLevel = -1;
        Decision dec = Decision::Vanilla;
        if (total >= 0 && nGot == nClass && nClass > 0) dec = levelNow(cIds, cLvls, nGot, preset, key, cfg->hold, &rec, &recLevel);
        const bool midloop = dec == Decision::Hold;   // the LevelUp hook can never veto: HOLD here = vanilla (engine picks)
        if (midloop) { rec = nullptr; recLevel = -1; }
        char recS[16]; if (recLevel >= 0) snprintf(recS, sizeof recS, "%d", recLevel); else strcpy(recS, "-");
        logf("  DECIDE tag=%s preset=%s key=%d decision=%s rec=%s", tag, preset->id, key, midloop ? "HOLD_MIDLOOP" : decisionName(dec), recS);
        const char* lt = preset->id;
        if (nSkills != NumSkills || !dp.deltasOk || !dp.featsOk || !dp.spellsOk || dp.fCnt > static_cast<uint32_t>(MaxPend) ||
            dp.sCnt > static_cast<uint32_t>(MaxPend)) {
            logf("  DRY tag=%s key=%d status=skipped-unreadable (skills=%u feats=%u spells=%u)", lt, key, nSkills, dp.fCnt, dp.sCnt);
            if (rewriteTag) logf("  SKIP skipped-unreadable %s key=%d - vanilla", lt, key);
        } else {
            Result res = computeRewrite(rec, pd, classSkillMask(stats));
            Buf d;
            formatDry(d, lt, key, res);
            logf("  %s", d.s);
            if (rewriteTag) {
                if (!viaAuto) {
                    logf("  SKIP manual %s key=%d flow=%s - player's picks kept (rewrite only under AutoLevelup)", lt, key, flow);
                } else if (!strcmp(res.status, "already")) {
                    logf("  ALREADY (replay) %s key=%d - no write", lt, key);
                } else if (strcmp(res.status, "rewrite")) {
                    logf("  SKIP %s %s key=%d - vanilla", res.status, lt, key);
                } else if (!ApplyEnabled || !g_cfg.apply) {
                    logf("  WOULD REWRITE %s key=%d (apply=0)", lt, key);
                } else if (applyRewrite(pending, pd, res, nSkills)) {
                    saferead::beginScope();   // the engine push helpers may have reallocated the arrays
                    PendDump after;
                    readPend(pending, nSkills, &after);
                    const bool ok = after.ok && after.featsOk && after.spellsOk && after.deltasOk && samePend(after.pd, res.p);
                    logf("  APPLIED tag=%s key=%d ok=%d", lt, key, ok);
                    logPend("after", after, nSkills);
                }
            }
        }
    } else if (cfg) {
        logf("  tag %s configured but preset %s not in table (table %s)", tag, g_cfg.presetId[cfg - g_cfg.tags], g_tableOk ? "ok" : "ERROR");
    }
    logClose();
}

// ---- gates (0.3.0-a): hold gate, instant gate, GUI guards, Auto OK backstop -------------------------------
// Every handler replaces a 5-byte `call rel32` (skip_original_bytes): it calls the real function itself and its return value becomes EAX.
// The handlers run every frame (hold gate) or on clicks (guards); they never write the log except on a state change.
constexpr int Cr_Stats = 0x1198;   // creature -> CSWSCreatureStats*
enum GateSite : unsigned { S_Opt = 100, S_Chain };
typedef int (__thiscall* CanLevelUp_t)(void* stats);
typedef void* (__thiscall* OptAccessor_t)(void* ecx);
typedef int (__thiscall* CharChange_t)(void* ecx);
typedef void* (__thiscall* GetCreature_t)(void* ecx);
typedef void* (__thiscall* PartyGet_t)(void* ecx, int idx);
typedef void* (__thiscall* TableGet_t)(void* ecx);

int g_engState = 0;   // 0 unchecked, 1 gate functions verified, 2 mismatch (all gates pass through)
bool engineOk() {
    if (!g_eng.checkCode) return true;
    if (!g_engState) {
        const bool ok = codeMatches(g_eng.canLevelUp, kCanLevelUpCode, sizeof kCanLevelUpCode) && codeMatches(g_eng.optAccessor, kOptAccessorCode, sizeof kOptAccessorCode) &&
                        codeMatches(g_eng.charChange, kCharChangeCode, sizeof kCharChangeCode) && codeMatches(g_eng.getCreature, kGetCreatureCode, sizeof kGetCreatureCode) &&
                        codeMatches(g_eng.partyGet, kPartyGetCode, sizeof kPartyGetCode) && codeMatches(g_eng.tableGet, kTableGetCode, sizeof kTableGetCode);
        g_engState = ok ? 1 : 2;
        if (!ok) logLine("ENGINE gate function bytes differ from the expected build - gates pass through (vanilla)");
    }
    return g_engState == 1;
}

// Common prologue: header, throttled config/table reload. False = pass through.
bool gateActive() {
    ensureHeader();
    reloadConfig();
    if (g_cfg.mode == Mode::Off) return false;
    reloadTable();
    return engineOk();
}

struct Eval {
    bool ok = false;            // tag readable, tag configured with a resolved preset, classes readable, decision valid
    char tag[32] = "";
    const TagCfg* cfg = nullptr;
    const Preset* p = nullptr;
    int key = 0;
    Decision d = Decision::Vanilla;
};
// creature may be 0 (tag then via stats+0x24); when given, its own +0x18 tag is tried first.
Eval evalStats(uintptr_t stats, uintptr_t creature) {
    Eval e;
    if (!stats) return e;
    if (!((creature && readCreatureTag(creature, e.tag, sizeof e.tag)) || readTag(stats, e.tag, sizeof e.tag))) return e;
    e.cfg = tagConfig(e.tag);
    if (!e.cfg || e.cfg->preset < 0 || !g_tableOk) return e;
    e.p = &g_presets[e.cfg->preset];
    uint8_t ids[4], lv[4]; int n, total;
    if (!readClasses(stats, ids, lv, &n, &total)) return e;
    e.key = total + 1;
    e.d = levelNow(ids, lv, n, e.p, e.key, e.cfg->hold, nullptr, nullptr);
    e.ok = true;
    return e;
}

// Log-on-change state (never per frame).
struct HoldState { char tag[32]; bool held; int key; };
HoldState g_holdState[MaxTagCfg];
int g_nHoldState = 0;
void noteHold(const char* tag, int key, bool held, unsigned site, bool real) {
    HoldState* s = nullptr;
    for (int i = 0; i < g_nHoldState; ++i) if (!_stricmp(g_holdState[i].tag, tag)) s = &g_holdState[i];
    if (!s) {
        if (g_nHoldState >= MaxTagCfg) return;
        s = &g_holdState[g_nHoldState++];
        snprintf(s->tag, sizeof s->tag, "%s", tag);
        s->held = false; s->key = 0;
    }
    if (held && (!s->held || s->key != key)) logLine("%s tag=%s key=%d site=0x%X", real ? "HOLD" : "WOULD HOLD", tag, key, site);
    else if (!held && s->held) logLine("UNHOLD tag=%s", tag);
    s->held = held; s->key = key;
}

int holdGate(unsigned site, void* stats) {
    saferead::beginScope();
    const int r = reinterpret_cast<CanLevelUp_t>(g_eng.canLevelUp)(stats);
    if (!r || !gateActive()) return r;
    Eval e = evalStats(reinterpret_cast<uintptr_t>(stats), 0);
    if (!e.ok) return r;
    const bool held = e.d == Decision::Hold, real = g_cfg.mode == Mode::Rewrite;
    noteHold(e.tag, e.key, held, site, real);
    return held && real ? 0 : r;
}

struct InstantKey { char tag[32]; int key; };
InstantKey g_instSeen[32];
int g_nInstSeen = 0, g_instNext = 0;
uint8_t g_instBuf[16];   // options copy handed back to the engine (read-only use: [p+8] & 1)

void* instantGate(unsigned site, int ebpOff, void* ecx, uintptr_t ebp) {
    saferead::beginScope();
    void* const p = reinterpret_cast<OptAccessor_t>(g_eng.optAccessor)(ecx);
    if (!p || !gateActive() || g_cfg.mode != Mode::Rewrite) return p;
    uint32_t cr = 0, stats = 0, flags = 0;
    if (!readAt(S_Chain, ebp, ebpOff, &cr) || !cr || !readAt(S_Stats, cr, Cr_Stats, &stats) || !stats) return p;
    Eval e = evalStats(stats, cr);
    if (!e.ok || !e.cfg->instant || e.d == Decision::Hold) return p;
    const uintptr_t pa = reinterpret_cast<uintptr_t>(p);
    if (!readAt(S_Opt, pa, 8, &flags) || (flags & 1) || !probeRead(S_Opt, p, sizeof g_instBuf)) return p;
    memcpy(g_instBuf, p, sizeof g_instBuf);
    g_instBuf[8] |= 1;
    bool seen = false;
    for (int i = 0; i < g_nInstSeen; ++i) if (g_instSeen[i].key == e.key && !_stricmp(g_instSeen[i].tag, e.tag)) seen = true;
    if (!seen) {
        InstantKey& k = g_instSeen[g_nInstSeen < 32 ? g_nInstSeen++ : (g_instNext++ & 31)];
        snprintf(k.tag, sizeof k.tag, "%s", e.tag); k.key = e.key;
        logLine("INSTANT tag=%s key=%d site=0x%X", e.tag, e.key, site);
    }
    return g_instBuf;
}

// Leader creature as the GUI sees it: 0x77D800(0x7E5DA0(0x73FB90([[0xA1B4A4]+4]), 0)); 0 on any null / unreadable link.
uintptr_t leaderCreature() {
    uint32_t app = 0, client = 0;
    if (!readAt(S_Chain, g_eng.appGlobal, 0, &app) || !app || !readAt(S_Chain, app, 4, &client) || !client) return 0;
    void* party = reinterpret_cast<TableGet_t>(g_eng.tableGet)(reinterpret_cast<void*>(static_cast<uintptr_t>(client)));
    if (!party) return 0;
    void* member = reinterpret_cast<PartyGet_t>(g_eng.partyGet)(party, 0);
    if (!member) return 0;
    return reinterpret_cast<uintptr_t>(reinterpret_cast<GetCreature_t>(g_eng.getCreature)(member));
}
// Held (hold enabled + rule says HOLD) evaluation of a creature object.
Eval evalCreature(uintptr_t cr) {
    uint32_t stats = 0;
    if (!cr || !readAt(S_Stats, cr, Cr_Stats, &stats)) return Eval();
    return evalStats(stats, cr);
}

int g_probeLines = 0;
int guiGuard(unsigned site, const char* what, void* ecx) {
    saferead::beginScope();
    const int r = reinterpret_cast<CharChange_t>(g_eng.charChange)(ecx);
    if (r || !gateActive()) return r;
    const uintptr_t cr = leaderCreature();
    uint32_t stats = 0;
    if (cr) readAt(S_Stats, cr, Cr_Stats, &stats);
    Eval e = evalStats(stats, cr);
    if (g_probeLines < 300) {   // the tag offset on this path is unverified: log what each route reads on every trigger (clicks, not frames)
        ++g_probeLines;
        char tc[32] = "", ts[32] = "";
        const bool okC = cr && readCreatureTag(cr, tc, sizeof tc);
        const bool okS = stats && readTag(stats, ts, sizeof ts);
        logLine("GUARD-PROBE %s site=0x%X leader=%08x stats=%08x tagCreature=%s tagStats=%s decision=%s", what, site, (unsigned)cr, (unsigned)stats,
                okC ? tc : "?", okS ? ts : "?", e.ok ? decisionName(e.d) : "n/a");
    }
    if (e.ok && e.d == Decision::Hold && g_cfg.mode == Mode::Rewrite) {
        logLine("GUARD %s tag=%s key=%d site=0x%X", what, e.tag, e.key, site);
        return 1;
    }
    return r;
}

void* autoOkBackstop(void* ecx) {
    saferead::beginScope();
    void* const c = reinterpret_cast<GetCreature_t>(g_eng.getCreature)(ecx);
    if (!c || !gateActive()) return c;
    Eval e = evalCreature(reinterpret_cast<uintptr_t>(c));
    if (e.ok && e.d == Decision::Hold && g_cfg.mode == Mode::Rewrite) {
        logLine("GUARD autook tag=%s key=%d site=0x850062", e.tag, e.key);
        return nullptr;
    }
    return c;
}

} // namespace

extern "C" {

// Hook 0x006B9870 (CSWSCreatureStats::LevelUp entry). Params in hooks.toml order: ecx, [esp+0], [esp+4], [esp+8], ebp.
void __cdecl LevelUpOverrideEntry(void* stats, void* ret, void* pending, int addToList, void* ebp) {
    saferead::beginScope();
    onLevelUp(reinterpret_cast<uintptr_t>(stats), reinterpret_cast<uintptr_t>(ret), reinterpret_cast<uintptr_t>(pending), addToList,
              reinterpret_cast<uintptr_t>(ebp));
}

// One export per call site so the handler knows its site. Hold gate: param ecx = stats. Instant gate: params ecx, ebp (creature = [ebp+OFF]).
#define LUO_HOLD(VA) int __cdecl LuoHold_##VA(void* stats) { return holdGate(0x##VA, stats); }
#define LUO_INSTANT(VA, OFF) void* __cdecl LuoInstant_##VA(void* ecx, void* ebp) { return instantGate(0x##VA, OFF, ecx, reinterpret_cast<uintptr_t>(ebp)); }
LUO_HOLD(74F3C7) LUO_HOLD(84F221) LUO_HOLD(5FD7CE) LUO_HOLD(5FE2A3) LUO_HOLD(66C95C) LUO_HOLD(5FEE32) LUO_HOLD(756DD4)
LUO_HOLD(7575B5) LUO_HOLD(757808) LUO_HOLD(75798C) LUO_HOLD(75218B) LUO_HOLD(7C9F3B) LUO_HOLD(75FCB8)
LUO_INSTANT(74F3E9, -0x38) LUO_INSTANT(5FD7A0, -0x14) LUO_INSTANT(5FE281, -0x18) LUO_INSTANT(66C93A, -8)

// GetCharacterChangeInProgress 0x740FC0 call sites (ecx).
int __cdecl LuoGuardGui_84FD2F(void* ecx) { return guiGuard(0x84FD2F, "gui", ecx); }
int __cdecl LuoGuardAuto_84F9FE(void* ecx) { return guiGuard(0x84F9FE, "auto", ecx); }
// DoAutoLevelup 0x77D800 call at 0x850062 (ecx).
void* __cdecl LuoAutoOk_850062(void* ecx) { return autoOkBackstop(ecx); }

} // extern "C"

BOOL WINAPI DllMain(HINSTANCE inst, DWORD reason, LPVOID) {
    if (reason == DLL_PROCESS_ATTACH) DisableThreadLibraryCalls(inst);
    return TRUE;
}
